
import { Team, Player, Fixture, DetailedPosition } from './types';

const firstNames = ['Lucas', 'Matheus', 'Gabriel', 'Pedro', 'João', 'Felipe', 'Rafael', 'Daniel', 'Bruno', 'Thiago', 'Marcos', 'André', 'Luiz', 'Gustavo', 'Eduardo', 'Caio', 'Enzo', 'Arthur', 'Diego', 'Victor', 'Ruan', 'Igor', 'Breno', 'Talles', 'Yuri'];
const lastNames = ['Silva', 'Santos', 'Oliveira', 'Souza', 'Rodrigues', 'Ferreira', 'Almeida', 'Pereira', 'Lima', 'Gomes', 'Costa', 'Martins', 'Araújo', 'Barbosa', 'Ramos', 'Jesus', 'Alves', 'Rocha', 'Nascimento', 'Teixeira', 'Moraes'];

const DETAILED_POS_MAP: Record<Player['position'], DetailedPosition[]> = {
  'GOL': ['GK'],
  'ZAG': ['CB'],
  'LAT': ['RB', 'LB'],
  'VOL': ['DM'],
  'MEI': ['CM', 'AM'],
  'ATA': ['ST', 'RW', 'LW']
};

const generatePlayer = (pos: Player['position'], baseRating: number): Player => {
  const isProspect = Math.random() > 0.8;
  const age = isProspect ? Math.floor(Math.random() * 4) + 17 : Math.floor(Math.random() * 15) + 21;
  const overall = Math.min(99, Math.max(40, baseRating + Math.floor(Math.random() * 10) - 5));
  const potential = Math.min(99, overall + (isProspect ? Math.floor(Math.random() * 15) + 5 : Math.floor(Math.random() * 5)));

  let baseValue = Math.pow(overall, 3.2) * 12;
  if (age < 22) baseValue *= 1.4;
  if (age > 31) baseValue *= 0.7;

  // New Detailed Logic
  const possibleDetails = DETAILED_POS_MAP[pos];
  const mainPosition = possibleDetails[Math.floor(Math.random() * possibleDetails.length)];
  
  const footRoll = Math.random();
  const preferredFoot: Player['preferredFoot'] = 
    footRoll > 0.30 ? 'RIGHT' : 
    footRoll > 0.05 ? 'LEFT' : 'BOTH';

  return {
    id: Math.random().toString(36).substr(2, 9),
    name: `${firstNames[Math.floor(Math.random() * firstNames.length)]} ${lastNames[Math.floor(Math.random() * lastNames.length)]}`,
    position: pos,
    mainPosition,
    secondaryPositions: [], // Start simple, add later if needed
    preferredFoot,
    age,
    overall,
    energy: 100,
    status: 'fit',
    yellowCards: 0,
    redCards: 0,
    marketValue: Math.round(baseValue / 1000) * 1000,
    goals: 0,
    assists: 0,
    potential,
    contractRounds: Math.floor(Math.random() * 20) + 15,
    history: [],
    seasonStats: {
      yellowCards: 0,
      redCards: 0,
      matchesSuspended: 0
    },
    stats: generateStats(mainPosition, overall, age)
  };
};

const generateStats = (detPos: DetailedPosition, ovr: number, age: number) => {
  const r = (base: number) => Math.min(99, Math.max(10, base + Math.floor(Math.random() * 12) - 6));
  
  // Initialize with mid values
  const stats = {
    pace: r(ovr), shooting: r(ovr * 0.7), passing: r(ovr * 0.7), dribbling: r(ovr * 0.7), 
    defending: r(ovr * 0.6), physical: r(ovr * 0.75), keeping: 10,
    crossing: r(ovr * 0.6), finishing: r(ovr * 0.6), tackling: r(ovr * 0.6), 
    marking: r(ovr * 0.6), positioning: r(ovr * 0.7), strength: r(ovr * 0.7), 
    stamina: r(ovr * 0.75), vision: r(ovr * 0.6), longShot: r(ovr * 0.5), 
    heading: r(ovr * 0.5), reflexes: 10, handling: 10
  };

  if (detPos === 'GK') {
    stats.keeping = r(ovr);
    stats.reflexes = r(ovr * 1.1);
    stats.handling = r(ovr * 0.9);
    stats.pace = r(40);
    stats.defending = r(50);
  } else if (['CB', 'DM'].includes(detPos)) {
    stats.defending = r(ovr);
    stats.marking = r(ovr * 0.95);
    stats.tackling = r(ovr * 0.9);
    stats.strength = r(ovr * 0.85);
    stats.heading = r(ovr * 0.7);
    stats.shooting = r(40);
  } else if (['RB', 'LB'].includes(detPos)) {
    stats.pace = r(ovr * 0.9);
    stats.stamina = r(ovr * 0.9);
    stats.crossing = r(ovr * 0.8);
    stats.defending = r(ovr * 0.75);
  } else if (['CM', 'AM'].includes(detPos)) {
    stats.passing = r(ovr);
    stats.vision = r(ovr * 0.95);
    stats.dribbling = r(ovr * 0.85);
    stats.longShot = r(ovr * 0.75);
  } else if (['ST', 'LW', 'RW'].includes(detPos)) {
    stats.pace = r(ovr * 0.85);
    stats.finishing = r(ovr * 0.95);
    stats.shooting = r(ovr);
    stats.dribbling = r(ovr * 0.85);
    stats.positioning = r(ovr * 0.9);
  }

  if (age > 30) {
    stats.pace -= 8;
    stats.stamina -= 5;
    stats.positioning += 5;
  }

  return stats;
};

const generateRoster = (teamRating: number): Player[] => {
  const roster: Player[] = [];
  ['GOL', 'GOL'].forEach(p => roster.push(generatePlayer(p as any, teamRating)));
  ['ZAG', 'ZAG', 'ZAG', 'ZAG'].forEach(p => roster.push(generatePlayer(p as any, teamRating)));
  ['LAT', 'LAT', 'LAT', 'LAT'].forEach(p => roster.push(generatePlayer(p as any, teamRating)));
  ['VOL', 'VOL', 'VOL', 'VOL'].forEach(p => roster.push(generatePlayer(p as any, teamRating)));
  ['MEI', 'MEI', 'MEI', 'MEI'].forEach(p => roster.push(generatePlayer(p as any, teamRating)));
  ['ATA', 'ATA', 'ATA', 'ATA'].forEach(p => roster.push(generatePlayer(p as any, teamRating)));
  return roster.sort((a, b) => b.overall - a.overall);
};

export const INITIAL_TEAMS: Team[] = [
  {
    "id": "athletico-pr",
    "name": "Athletico Paranaense",
    "shortName": "CAP",
    "city": "Curitiba",
    "logoColor1": "from-red-600",
    "logoColor2": "to-black",
    "logoUrl": "/logos/athletico-pr.png",
    "attack": 87,
    "defense": 86,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 85,
    "division": 1,
    "stadiumCapacity": 42000,
    "stadiumName": "Ligga Arena",
    "socioCount": 40000,
    "financeStatus": "Boa",
    "seasonExpectation": "G6"
  },
  {
    "id": "atletico-mg",
    "name": "Atlético-MG",
    "shortName": "CAM",
    "city": "Belo Horizonte",
    "logoColor1": "from-gray-900",
    "logoColor2": "to-white",
    "logoUrl": "/logos/atletico-mg.png",
    "attack": 90,
    "defense": 89,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 90,
    "division": 1,
    "stadiumCapacity": 46000,
    "stadiumName": "Arena MRV",
    "socioCount": 100000,
    "rivalId": "cruzeiro",
    "financeStatus": "Boa",
    "seasonExpectation": "Título"
  },
  {
    "id": "bahia",
    "name": "Bahia",
    "shortName": "BAH",
    "city": "Salvador",
    "logoColor1": "from-blue-600",
    "logoColor2": "to-red-600",
    "logoUrl": "/logos/bahia.png",
    "attack": 88,
    "defense": 87,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 88,
    "division": 1,
    "stadiumCapacity": 48000,
    "stadiumName": "Arena Fonte Nova",
    "socioCount": 60000,
    "rivalId": "vitoria",
    "financeStatus": "Boa",
    "seasonExpectation": "Libertadores"
  },
  {
    "id": "botafogo",
    "name": "Botafogo",
    "shortName": "BOT",
    "city": "Rio de Janeiro",
    "logoColor1": "from-black",
    "logoColor2": "to-white",
    "logoUrl": "/logos/botafogo.png",
    "attack": 91,
    "defense": 90,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 92,
    "division": 1,
    "stadiumCapacity": 46000,
    "stadiumName": "Nilton Santos",
    "socioCount": 70000,
    "rivalId": "flamengo",
    "financeStatus": "Rico",
    "seasonExpectation": "Título"
  },
  {
    "id": "chapecoense",
    "name": "Chapecoense",
    "shortName": "CHA",
    "city": "Chapecó",
    "logoColor1": "from-green-600",
    "logoColor2": "to-white",
    "logoUrl": "/logos/chapecoense.png",
    "attack": 82,
    "defense": 81,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 75,
    "division": 1,
    "stadiumCapacity": 20000,
    "stadiumName": "Arena Condá",
    "socioCount": 15000,
    "financeStatus": "Controlada",
    "seasonExpectation": "Meio"
  },
  {
    "id": "corinthians",
    "name": "Corinthians",
    "shortName": "COR",
    "city": "São Paulo",
    "logoColor1": "from-black",
    "logoColor2": "to-white",
    "logoUrl": "/logos/corinthians.png",
    "attack": 86,
    "defense": 85,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 80,
    "division": 1,
    "stadiumCapacity": 49000,
    "stadiumName": "Neo Química Arena",
    "socioCount": 120000,
    "rivalId": "palmeiras",
    "financeStatus": "Boa",
    "seasonExpectation": "Libertadores"
  },
  {
    "id": "coritiba",
    "name": "Coritiba",
    "shortName": "CFC",
    "city": "Curitiba",
    "logoColor1": "from-green-700",
    "logoColor2": "to-white",
    "logoUrl": "/logos/coritiba.png",
    "attack": 83,
    "defense": 82,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 78,
    "division": 1,
    "stadiumCapacity": 40000,
    "stadiumName": "Couto Pereira",
    "socioCount": 30000,
    "rivalId": "athletico-pr",
    "financeStatus": "Boa",
    "seasonExpectation": "Meio"
  },
  {
    "id": "cruzeiro",
    "name": "Cruzeiro",
    "shortName": "CRU",
    "city": "Belo Horizonte",
    "logoColor1": "from-blue-700",
    "logoColor2": "to-white",
    "logoUrl": "/logos/cruzeiro.png",
    "attack": 89,
    "defense": 88,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 88,
    "division": 1,
    "stadiumCapacity": 62000,
    "stadiumName": "Mineirão",
    "socioCount": 90000,
    "rivalId": "atletico-mg",
    "financeStatus": "Rico",
    "seasonExpectation": "G4"
  },
  {
    "id": "flamengo",
    "name": "Flamengo",
    "shortName": "FLA",
    "city": "Rio de Janeiro",
    "logoColor1": "from-red-600",
    "logoColor2": "to-black",
    "logoUrl": "/logos/flamengo.png",
    "attack": 95,
    "defense": 94,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 98,
    "division": 1,
    "stadiumCapacity": 78000,
    "stadiumName": "Maracanã",
    "socioCount": 160000,
    "rivalId": "vasco",
    "financeStatus": "Rico",
    "seasonExpectation": "Campeão"
  },
  {
    "id": "fluminense",
    "name": "Fluminense",
    "shortName": "FLU",
    "city": "Rio de Janeiro",
    "logoColor1": "from-green-700",
    "logoColor2": "to-red-700",
    "logoUrl": "/logos/fluminense.png",
    "attack": 88,
    "defense": 87,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 85,
    "division": 1,
    "stadiumCapacity": 78000,
    "stadiumName": "Maracanã",
    "socioCount": 80000,
    "rivalId": "flamengo",
    "financeStatus": "Boa",
    "seasonExpectation": "G6"
  },
  {
    "id": "gremio",
    "name": "Grêmio",
    "shortName": "GRE",
    "city": "Porto Alegre",
    "logoColor1": "from-blue-500",
    "logoColor2": "to-black",
    "logoUrl": "/logos/gremio.png",
    "attack": 87,
    "defense": 86,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 82,
    "division": 1,
    "stadiumCapacity": 55000,
    "stadiumName": "Arena do Grêmio",
    "socioCount": 90000,
    "rivalId": "internacional",
    "financeStatus": "Boa",
    "seasonExpectation": "G6"
  },
  {
    "id": "internacional",
    "name": "Internacional",
    "shortName": "INT",
    "city": "Porto Alegre",
    "logoColor1": "from-red-600",
    "logoColor2": "to-white",
    "logoUrl": "/logos/internacional.png",
    "attack": 87,
    "defense": 86,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 84,
    "division": 1,
    "stadiumCapacity": 50000,
    "stadiumName": "Beira-Rio",
    "socioCount": 110000,
    "rivalId": "gremio",
    "financeStatus": "Boa",
    "seasonExpectation": "G6"
  },
  {
    "id": "mirassol",
    "name": "Mirassol",
    "shortName": "MIR",
    "city": "Mirassol",
    "logoColor1": "from-yellow-400",
    "logoColor2": "to-green-600",
    "logoUrl": "/logos/mirassol.png",
    "attack": 84,
    "defense": 83,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 80,
    "division": 1,
    "stadiumCapacity": 15000,
    "stadiumName": "Maião",
    "socioCount": 10000,
    "financeStatus": "Boa",
    "seasonExpectation": "Meio"
  },
  {
    "id": "palmeiras",
    "name": "Palmeiras",
    "shortName": "PAL",
    "city": "São Paulo",
    "logoColor1": "from-green-700",
    "logoColor2": "to-white",
    "logoUrl": "/logos/palmeiras.png",
    "attack": 94,
    "defense": 93,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 95,
    "division": 1,
    "stadiumCapacity": 43000,
    "stadiumName": "Allianz Parque",
    "socioCount": 150000,
    "rivalId": "corinthians",
    "financeStatus": "Rico",
    "seasonExpectation": "Campeão"
  },
  {
    "id": "bragantino",
    "name": "Red Bull Bragantino",
    "shortName": "RBB",
    "city": "Bragança Paulista",
    "logoColor1": "from-white",
    "logoColor2": "to-red-600",
    "logoUrl": "/logos/bragantino.png",
    "attack": 86,
    "defense": 85,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 82,
    "division": 1,
    "stadiumCapacity": 17000,
    "stadiumName": "Nabi Abi Chedid",
    "socioCount": 12000,
    "financeStatus": "Boa",
    "seasonExpectation": "G6"
  },
  {
    "id": "remo",
    "name": "Remo",
    "shortName": "REM",
    "city": "Belém",
    "logoColor1": "from-blue-900",
    "logoColor2": "to-white",
    "logoUrl": "/logos/remo.png",
    "attack": 81,
    "defense": 80,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Defensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 75,
    "division": 1,
    "stadiumCapacity": 13000,
    "stadiumName": "Baenão",
    "socioCount": 25000,
    "rivalId": "paysandu",
    "financeStatus": "Controlada",
    "seasonExpectation": "Meio"
  },
  {
    "id": "santos",
    "name": "Santos",
    "shortName": "SAN",
    "city": "Santos",
    "logoColor1": "from-white",
    "logoColor2": "to-black",
    "logoUrl": "/logos/santos.png",
    "attack": 88,
    "defense": 87,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 88,
    "division": 1,
    "stadiumCapacity": 16000,
    "stadiumName": "Vila Belmiro",
    "socioCount": 70000,
    "rivalId": "corinthians",
    "financeStatus": "Boa",
    "seasonExpectation": "Libertadores"
  },
  {
    "id": "saopaulo",
    "name": "São Paulo",
    "shortName": "SAO",
    "city": "São Paulo",
    "logoColor1": "from-red-600",
    "logoColor2": "to-white",
    "logoUrl": "/logos/saopaulo.png",
    "attack": 89,
    "defense": 88,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 88,
    "division": 1,
    "stadiumCapacity": 66000,
    "stadiumName": "Morumbi",
    "socioCount": 110000,
    "rivalId": "corinthians",
    "financeStatus": "Boa",
    "seasonExpectation": "G4"
  },
  {
    "id": "vasco",
    "name": "Vasco da Gama",
    "shortName": "VAS",
    "city": "Rio de Janeiro",
    "logoColor1": "from-black",
    "logoColor2": "to-white",
    "logoUrl": "/logos/vasco.png",
    "attack": 87,
    "defense": 86,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 82,
    "division": 1,
    "stadiumCapacity": 21000,
    "stadiumName": "São Januário",
    "socioCount": 85000,
    "rivalId": "flamengo",
    "financeStatus": "Boa",
    "seasonExpectation": "G8"
  },
  {
    "id": "vitoria",
    "name": "Vitória",
    "shortName": "VIT",
    "city": "Salvador",
    "logoColor1": "from-red-600",
    "logoColor2": "to-black",
    "logoUrl": "/logos/vitoria.png",
    "attack": 83,
    "defense": 82,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 78,
    "division": 1,
    "stadiumCapacity": 30000,
    "stadiumName": "Barradão",
    "socioCount": 40000,
    "rivalId": "bahia",
    "financeStatus": "Controlada",
    "seasonExpectation": "Meio"
  },
  {
    "id": "america-mg",
    "name": "América Mineiro",
    "shortName": "AMG",
    "city": "Belo Horizonte",
    "logoColor1": "from-green-600",
    "logoColor2": "to-black",
    "logoUrl": "/logos/america-mg.png",
    "attack": 78,
    "defense": 77,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 75,
    "division": 2,
    "stadiumCapacity": 23000,
    "stadiumName": "Independência",
    "socioCount": 20000,
    "financeStatus": "Boa",
    "seasonExpectation": "Acesso"
  },
  {
    "id": "athletic",
    "name": "Athletic",
    "shortName": "ATH",
    "city": "São João del-Rei",
    "logoColor1": "from-black",
    "logoColor2": "to-white",
    "logoUrl": "/logos/athletic.png",
    "attack": 74,
    "defense": 73,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 72,
    "division": 2,
    "stadiumCapacity": 4000,
    "stadiumName": "Mário Helênio",
    "socioCount": 5000,
    "financeStatus": "Controlada",
    "seasonExpectation": "Meio"
  },
  {
    "id": "atletico-go",
    "name": "Atlético Goianiense",
    "shortName": "ACG",
    "city": "Goiânia",
    "logoColor1": "from-red-600",
    "logoColor2": "to-black",
    "logoUrl": "/logos/atletico-go.png",
    "attack": 79,
    "defense": 78,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 78,
    "division": 2,
    "stadiumCapacity": 12000,
    "stadiumName": "Antônio Accioly",
    "socioCount": 15000,
    "rivalId": "goias",
    "financeStatus": "Boa",
    "seasonExpectation": "Acesso"
  },
  {
    "id": "avai",
    "name": "Avaí",
    "shortName": "AVA",
    "city": "Florianópolis",
    "logoColor1": "from-blue-600",
    "logoColor2": "to-white",
    "logoUrl": "/logos/avai.png",
    "attack": 76,
    "defense": 75,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Defensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 70,
    "division": 2,
    "stadiumCapacity": 17000,
    "stadiumName": "Ressacada",
    "socioCount": 18000,
    "financeStatus": "Controlada",
    "seasonExpectation": "G8"
  },
  {
    "id": "botafogo-sp",
    "name": "Botafogo-SP",
    "shortName": "BSP",
    "city": "Ribeirão Preto",
    "logoColor1": "from-red-600",
    "logoColor2": "to-white",
    "logoUrl": "/logos/botafogo-sp.png",
    "attack": 73,
    "defense": 72,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 68,
    "division": 2,
    "stadiumCapacity": 28000,
    "stadiumName": "Santa Cruz",
    "socioCount": 10000,
    "financeStatus": "Controlada",
    "seasonExpectation": "Meio"
  },
  {
    "id": "crb",
    "name": "CRB",
    "shortName": "CRB",
    "city": "Maceió",
    "logoColor1": "from-red-600",
    "logoColor2": "to-white",
    "logoUrl": "/logos/crb.png",
    "attack": 75,
    "defense": 74,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 72,
    "division": 2,
    "stadiumCapacity": 18000,
    "stadiumName": "Rei Pelé",
    "socioCount": 15000,
    "financeStatus": "Boa",
    "seasonExpectation": "G8"
  },
  {
    "id": "ceara",
    "name": "Ceará",
    "shortName": "CEA",
    "city": "Fortaleza",
    "logoColor1": "from-black",
    "logoColor2": "to-white",
    "logoUrl": "/logos/ceara.png",
    "attack": 79,
    "defense": 78,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 80,
    "division": 2,
    "stadiumCapacity": 63000,
    "stadiumName": "Castelão",
    "socioCount": 45000,
    "rivalId": "fortaleza",
    "financeStatus": "Boa",
    "seasonExpectation": "Acesso"
  },
  {
    "id": "criciuma",
    "name": "Criciúma",
    "shortName": "CRI",
    "city": "Criciúma",
    "logoColor1": "from-yellow-400",
    "logoColor2": "to-black",
    "logoUrl": "/logos/criciuma.png",
    "attack": 78,
    "defense": 77,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 76,
    "division": 2,
    "stadiumCapacity": 19000,
    "stadiumName": "Heriberto Hülse",
    "socioCount": 22000,
    "financeStatus": "Boa",
    "seasonExpectation": "G8"
  },
  {
    "id": "cuiaba",
    "name": "Cuiabá",
    "shortName": "CUI",
    "city": "Cuiabá",
    "logoColor1": "from-green-700",
    "logoColor2": "to-yellow-500",
    "logoUrl": "/logos/cuiaba.png",
    "attack": 77,
    "defense": 76,
    "roster": [],
    "lineup": [],
    "formation": "5-4-1",
    "style": "Defensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 74,
    "division": 2,
    "stadiumCapacity": 44000,
    "stadiumName": "Arena Pantanal",
    "socioCount": 20000,
    "financeStatus": "Boa",
    "seasonExpectation": "Acesso"
  },
  {
    "id": "fortaleza",
    "name": "Fortaleza",
    "shortName": "FOR",
    "city": "Fortaleza",
    "logoColor1": "from-blue-600",
    "logoColor2": "to-red-600",
    "logoUrl": "/logos/fortaleza.png",
    "attack": 80,
    "defense": 79,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 82,
    "division": 2,
    "stadiumCapacity": 63000,
    "stadiumName": "Castelão",
    "socioCount": 45000,
    "rivalId": "ceara",
    "financeStatus": "Boa",
    "seasonExpectation": "Acesso"
  },
  {
    "id": "goias",
    "name": "Goiás",
    "shortName": "GOI",
    "city": "Goiânia",
    "logoColor1": "from-green-600",
    "logoColor2": "to-white",
    "logoUrl": "/logos/goias.png",
    "attack": 77,
    "defense": 76,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 74,
    "division": 2,
    "stadiumCapacity": 14000,
    "stadiumName": "Serrinha",
    "socioCount": 28000,
    "rivalId": "atletico-go",
    "financeStatus": "Boa",
    "seasonExpectation": "Acesso"
  },
  {
    "id": "juventude",
    "name": "Juventude",
    "shortName": "JUV",
    "city": "Caxias do Sul",
    "logoColor1": "from-green-600",
    "logoColor2": "to-white",
    "logoUrl": "/logos/juventude.png",
    "attack": 76,
    "defense": 75,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Defensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 71,
    "division": 2,
    "stadiumCapacity": 19000,
    "stadiumName": "Alfredo Jaconi",
    "socioCount": 15000,
    "financeStatus": "Controlada",
    "seasonExpectation": "G8"
  },
  {
    "id": "londrina",
    "name": "Londrina",
    "shortName": "LEC",
    "city": "Londrina",
    "logoColor1": "from-blue-400",
    "logoColor2": "to-white",
    "logoUrl": "/logos/londrina.png",
    "attack": 72,
    "defense": 71,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 68,
    "division": 2,
    "stadiumCapacity": 30000,
    "stadiumName": "Estádio do Café",
    "socioCount": 12000,
    "financeStatus": "Controlada",
    "seasonExpectation": "Meio"
  },
  {
    "id": "novorizontino",
    "name": "Novorizontino",
    "shortName": "NOV",
    "city": "Novo Horizonte",
    "logoColor1": "from-yellow-400",
    "logoColor2": "to-black",
    "logoUrl": "/logos/novorizontino.png",
    "attack": 74,
    "defense": 73,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 70,
    "division": 2,
    "stadiumCapacity": 12000,
    "stadiumName": "Jorjão",
    "socioCount": 8000,
    "financeStatus": "Boa",
    "seasonExpectation": "G8"
  },
  {
    "id": "nautico",
    "name": "Náutico",
    "shortName": "NAU",
    "city": "Recife",
    "logoColor1": "from-red-600",
    "logoColor2": "to-white",
    "logoUrl": "/logos/nautico.png",
    "attack": 73,
    "defense": 72,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 75,
    "division": 2,
    "stadiumCapacity": 22000,
    "stadiumName": "Aflitos",
    "socioCount": 25000,
    "rivalId": "sport",
    "financeStatus": "Controlada",
    "seasonExpectation": "G8"
  },
  {
    "id": "operario",
    "name": "Operário PR",
    "shortName": "OPE",
    "city": "Ponta Grossa",
    "logoColor1": "from-black",
    "logoColor2": "to-white",
    "logoUrl": "/logos/operario.png",
    "attack": 73,
    "defense": 72,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Defensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 70,
    "division": 2,
    "stadiumCapacity": 10000,
    "stadiumName": "Germano Krüger",
    "socioCount": 10000,
    "financeStatus": "Controlada",
    "seasonExpectation": "Meio"
  },
  {
    "id": "ponte-preta",
    "name": "Ponte Preta",
    "shortName": "PON",
    "city": "Campinas",
    "logoColor1": "from-black",
    "logoColor2": "to-white",
    "logoUrl": "/logos/ponte-preta.png",
    "attack": 74,
    "defense": 73,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 72,
    "division": 2,
    "stadiumCapacity": 19000,
    "stadiumName": "Moisés Lucarelli",
    "socioCount": 22000,
    "financeStatus": "Boa",
    "seasonExpectation": "G8"
  },
  {
    "id": "sport",
    "name": "Sport",
    "shortName": "SPT",
    "city": "Recife",
    "logoColor1": "from-red-600",
    "logoColor2": "to-black",
    "logoUrl": "/logos/sport.png",
    "attack": 79,
    "defense": 78,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Ofensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 80,
    "division": 2,
    "stadiumCapacity": 35000,
    "stadiumName": "Ilha do Retiro",
    "socioCount": 45000,
    "rivalId": "nautico",
    "financeStatus": "Boa",
    "seasonExpectation": "Acesso"
  },
  {
    "id": "sao-bernardo",
    "name": "São Bernardo",
    "shortName": "SBE",
    "city": "São Bernardo do Campo",
    "logoColor1": "from-yellow-400",
    "logoColor2": "to-black",
    "logoUrl": "/logos/sao-bernardo.png",
    "attack": 72,
    "defense": 71,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Defensivo",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 67,
    "division": 2,
    "stadiumCapacity": 15000,
    "stadiumName": "1º de Maio",
    "socioCount": 8000,
    "financeStatus": "Controlada",
    "seasonExpectation": "Meio"
  },
  {
    "id": "vila-nova",
    "name": "Vila Nova",
    "shortName": "VIL",
    "city": "Goiânia",
    "logoColor1": "from-red-600",
    "logoColor2": "to-white",
    "logoUrl": "/logos/vila-nova.png",
    "attack": 75,
    "defense": 74,
    "roster": [],
    "lineup": [],
    "formation": "4-4-2",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 74,
    "division": 2,
    "stadiumCapacity": 11000,
    "stadiumName": "OBA",
    "socioCount": 15000,
    "rivalId": "goias",
    "financeStatus": "Boa",
    "seasonExpectation": "G8"
  },
  {
    "id": "free_agent",
    "name": "Sem Clube",
    "shortName": "LIV",
    "city": "Mundo",
    "logoColor1": "from-gray-500",
    "logoColor2": "to-gray-700",
    "attack": 70,
    "defense": 70,
    "roster": [],
    "lineup": [],
    "formation": "4-3-3",
    "style": "Equilibrado",
    "played": 0,
    "won": 0,
    "drawn": 0,
    "lost": 0,
    "gf": 0,
    "ga": 0,
    "points": 0,
    "moral": 50,
    "division": 0,
    "stadiumCapacity": 0,
    "description": "Jogadores sem clube disponíveis no mercado."
  }
];

INITIAL_TEAMS.forEach(team => {
  if (team.id === 'free_agent') {
    // Gerar 30 jogadores variados para Free Agents
    const roster: Player[] = [];
    for (let i = 0; i < 30; i++) {
      const positions = ['GOL', 'ZAG', 'LAT', 'VOL', 'MEI', 'ATA'];
      const pos = positions[Math.floor(Math.random() * positions.length)];
      const rating = Math.floor(Math.random() * (85 - 55) + 55); // OVR entre 55 e 85
      roster.push(generatePlayer(pos as any, rating));
    }
    team.roster = roster.sort((a, b) => b.overall - a.overall);
  } else {
    const rating = Math.floor((team.attack + team.defense) / 2);
    team.roster = generateRoster(rating);
    team.lineup = team.roster.slice(0, 11).map(p => p.id);
  }
});

export const generateSchedule = (teams: Team[]): Fixture[] => {
  const fixtures: Fixture[] = [];
  const div1Ids = teams.filter(t => t.division === 1).map(t => t.id);
  const div2Ids = teams.filter(t => t.division === 2).map(t => t.id);
  const generateForIds = (ids: string[], startRound: number) => {
    const rotation = [...ids];
    const n = ids.length;
    for (let r = 0; r < n - 1; r++) {
      for (let i = 0; i < n / 2; i++) {
        fixtures.push({ round: startRound + r, homeTeamId: rotation[i], awayTeamId: rotation[n - 1 - i], played: false });
        fixtures.push({ round: startRound + r + (n - 1), homeTeamId: rotation[n - 1 - i], awayTeamId: rotation[i], played: false });
      }
      const last = rotation.pop()!;
      rotation.splice(1, 0, last);
    }
  };
  generateForIds(div1Ids, 1);
  generateForIds(div2Ids, 1);
  return fixtures.sort((a, b) => a.round - b.round);
};
