import { Team, Player, DetailedPosition } from './types';
import { selectBestLineupForFormation } from './engine/tacticsEngine';
import { createSouthAmericanRoster } from './southAmericanRosterFactory';

const generateStats = (detPos: DetailedPosition, ovr: number) => {
  const r = (base: number) => Math.min(99, Math.max(10, Math.round(base)));
  const stats = {
    pace: r(ovr * 0.8), shooting: r(ovr * 0.7), passing: r(ovr * 0.75), dribbling: r(ovr * 0.75),
    defending: r(ovr * 0.6), physical: r(ovr * 0.8), keeping: 10,
    crossing: r(ovr * 0.7), finishing: r(ovr * 0.7), tackling: r(ovr * 0.6),
    marking: r(ovr * 0.6), positioning: r(ovr * 0.75), strength: r(ovr * 0.8),
    stamina: r(ovr * 0.8), vision: r(ovr * 0.75), longShot: r(ovr * 0.65),
    heading: r(ovr * 0.65), reflexes: 10, handling: 10
  };

  if (detPos === 'GK') {
    stats.keeping = r(ovr * 0.95);
    stats.reflexes = r(ovr * 1.05);
    stats.handling = r(ovr * 0.9);
    stats.pace = r(40);
  } else if (['CB', 'DM'].includes(detPos)) {
    stats.defending = r(ovr * 0.95);
    stats.marking = r(ovr * 0.9);
    stats.tackling = r(ovr * 0.9);
    stats.strength = r(ovr * 0.85);
  } else if (['ST', 'LW', 'RW'].includes(detPos)) {
    stats.finishing = r(ovr * 0.95);
    stats.shooting = r(ovr * 0.9);
    stats.pace = r(ovr * 0.85);
  }
  return stats;
};

const createPlayer = (id: string, name: string, pos: Player['position'], mainPos: DetailedPosition, ovr: number, age: number, foot: 'LEFT' | 'RIGHT' | 'BOTH' = 'RIGHT'): Player => {
  const baseVal = Math.pow(ovr, 3.2) * 12 * (age < 23 ? 1.3 : age > 31 ? 0.75 : 1);
  return {
    id,
    name,
    position: pos,
    mainPosition: mainPos,
    secondaryPositions: [],
    preferredFoot: foot,
    age,
    overall: ovr,
    energy: 100,
    status: 'fit',
    yellowCards: 0,
    redCards: 0,
    marketValue: Math.round(baseVal / 1000) * 1000,
    goals: 0,
    assists: 0,
    potential: Math.min(99, ovr + (age < 22 ? 8 : 2)),
    contractRounds: 38,
    history: [],
    seasonStats: { yellowCards: 0, redCards: 0, matchesSuspended: 0 },
    stats: generateStats(mainPos, ovr)
  };
};

export const SOUTH_AMERICAN_FOREIGN_CLUBS: Omit<Team, 'instructions'>[] = [
  {
    id: 'boca-juniors',
    name: 'Boca Juniors',
    shortName: 'BOC',
    city: 'Buenos Aires',
    logoColor1: 'from-blue-700',
    logoColor2: 'to-yellow-500',
    logoUrl: '/logos/boca.svg',
    attack: 88,
    defense: 86,
    roster: [
      createPlayer('boc-1', 'Sergio Romero', 'GOL', 'GK', 81, 37),
      createPlayer('boc-2', 'Leandro Brey', 'GOL', 'GK', 75, 21),
      createPlayer('boc-3', 'Marcos Rojo', 'ZAG', 'CB', 80, 34, 'LEFT'),
      createPlayer('boc-4', 'Cristian Lema', 'ZAG', 'CB', 78, 34),
      createPlayer('boc-5', 'Aaron Anselmino', 'ZAG', 'CB', 79, 19),
      createPlayer('boc-6', 'Luis Advíncula', 'LAT', 'RB', 82, 34),
      createPlayer('boc-7', 'Lautaro Blanco', 'LAT', 'LB', 79, 25, 'LEFT'),
      createPlayer('boc-8', 'Pol Fernández', 'VOL', 'DM', 79, 32),
      createPlayer('boc-9', 'Cristian Medina', 'MEI', 'CM', 82, 22),
      createPlayer('boc-10', 'Kevin Zenón', 'MEI', 'AM', 83, 23, 'LEFT'),
      createPlayer('boc-11', 'Tomas Belmonte', 'VOL', 'DM', 78, 26),
      createPlayer('boc-12', 'Edinson Cavani', 'ATA', 'ST', 86, 37, 'RIGHT'),
      createPlayer('boc-13', 'Miguel Merentiel', 'ATA', 'ST', 84, 28),
      createPlayer('boc-14', 'Exequiel Zeballos', 'ATA', 'LW', 80, 22),
      createPlayer('boc-15', 'Milton Giménez', 'ATA', 'ST', 78, 27)
    ],
    lineup: ['boc-1', 'boc-6', 'boc-3', 'boc-5', 'boc-7', 'boc-8', 'boc-9', 'boc-10', 'boc-14', 'boc-12', 'boc-13'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 88,
    division: 1, stadiumCapacity: 54000, stadiumName: 'La Bombonera', socioCount: 300000
  },
  {
    id: 'river-plate',
    name: 'River Plate',
    shortName: 'RIV',
    city: 'Buenos Aires',
    logoColor1: 'from-red-600',
    logoColor2: 'to-white',
    logoUrl: '/logos/river.svg',
    attack: 90,
    defense: 88,
    roster: [
      createPlayer('riv-1', 'Franco Armani', 'GOL', 'GK', 83, 37),
      createPlayer('riv-2', 'Jeremías Ledesma', 'GOL', 'GK', 79, 31),
      createPlayer('riv-3', 'Germán Pezzella', 'ZAG', 'CB', 83, 33),
      createPlayer('riv-4', 'Paulo Díaz', 'ZAG', 'CB', 82, 29),
      createPlayer('riv-5', 'Landro González Pirez', 'ZAG', 'CB', 78, 32),
      createPlayer('riv-6', 'Fabricio Bustos', 'LAT', 'RB', 80, 28),
      createPlayer('riv-7', 'Marcos Acuña', 'LAT', 'LB', 84, 32, 'LEFT'),
      createPlayer('riv-8', 'Matias Kranevitter', 'VOL', 'DM', 78, 31),
      createPlayer('riv-9', 'Nacho Fernández', 'MEI', 'CM', 82, 34, 'LEFT'),
      createPlayer('riv-10', 'Manuel Lanzini', 'MEI', 'AM', 81, 31),
      createPlayer('riv-11', 'Claudio Echeverri', 'MEI', 'AM', 83, 18),
      createPlayer('riv-12', 'Franco Mastantuono', 'MEI', 'AM', 82, 17, 'LEFT'),
      createPlayer('riv-13', 'Miguel Borja', 'ATA', 'ST', 86, 31),
      createPlayer('riv-14', 'Facundo Colidio', 'ATA', 'LW', 81, 24),
      createPlayer('riv-15', 'Pablo Solari', 'ATA', 'RW', 81, 23)
    ],
    lineup: ['riv-1', 'riv-6', 'riv-3', 'riv-4', 'riv-7', 'riv-8', 'riv-9', 'riv-11', 'riv-15', 'riv-13', 'riv-14'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 90,
    division: 1, stadiumCapacity: 84000, stadiumName: 'MÂS Monumental', socioCount: 350000
  },
  {
    id: 'penarol',
    name: 'Peñarol',
    shortName: 'PEN',
    city: 'Montevideo',
    logoColor1: 'from-yellow-400',
    logoColor2: 'to-black',
    logoUrl: '/logos/penarol.svg',
    attack: 84,
    defense: 83,
    roster: [
      createPlayer('pen-1', 'Washington Aguerre', 'GOL', 'GK', 80, 31),
      createPlayer('pen-2', 'Javier Méndez', 'ZAG', 'CB', 79, 29),
      createPlayer('pen-3', 'Guzmán Rodríguez', 'ZAG', 'CB', 78, 24),
      createPlayer('pen-4', 'Pedro Milans', 'LAT', 'RB', 76, 22),
      createPlayer('pen-5', 'Lucas Hernández', 'LAT', 'LB', 77, 31, 'LEFT'),
      createPlayer('pen-6', 'Damían García', 'VOL', 'DM', 80, 20),
      createPlayer('pen-7', 'Eduardo Darias', 'MEI', 'CM', 79, 26),
      createPlayer('pen-8', 'Gastón Ramírez', 'MEI', 'AM', 79, 33, 'LEFT'),
      createPlayer('pen-9', 'Leonardo Sequeira', 'ATA', 'RW', 78, 29),
      createPlayer('pen-10', 'Jaime Báez', 'ATA', 'LW', 79, 29),
      createPlayer('pen-11', 'Maximiliano Silvera', 'ATA', 'ST', 82, 26),
      createPlayer('pen-12', 'Facundo Batista', 'ATA', 'ST', 77, 25)
    ],
    lineup: ['pen-1', 'pen-4', 'pen-2', 'pen-3', 'pen-5', 'pen-6', 'pen-7', 'pen-8', 'pen-9', 'pen-11', 'pen-10'],
    formation: '4-2-3-1',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 85,
    division: 1, stadiumCapacity: 40000, stadiumName: 'Campeón del Siglo', socioCount: 65000
  },
  {
    id: 'nacional-uru',
    name: 'Nacional',
    shortName: 'NAC',
    city: 'Montevideo',
    logoColor1: 'from-blue-600',
    logoColor2: 'to-white',
    logoUrl: '/logos/nacional.svg',
    attack: 83,
    defense: 82,
    roster: [
      createPlayer('nac-1', 'Luis Mejía', 'GOL', 'GK', 80, 33),
      createPlayer('nac-2', 'Sebastian Coates', 'ZAG', 'CB', 82, 33),
      createPlayer('nac-3', 'Diego Polenta', 'ZAG', 'CB', 78, 32, 'LEFT'),
      createPlayer('nac-4', 'Leandro Lozano', 'LAT', 'RB', 78, 25),
      createPlayer('nac-5', 'Gabriel Báez', 'LAT', 'LB', 76, 29),
      createPlayer('nac-6', 'Christian Oliva', 'VOL', 'DM', 78, 28),
      createPlayer('nac-7', 'Lucas Sanabria', 'MEI', 'CM', 80, 20),
      createPlayer('nac-8', 'Mauricio Pereyra', 'MEI', 'AM', 80, 34, 'LEFT'),
      createPlayer('nac-9', 'Antonio Galeano', 'ATA', 'RW', 77, 24),
      createPlayer('nac-10', 'Alexis Castro', 'MEI', 'CM', 78, 29),
      createPlayer('nac-11', 'Gonzalo Carneiro', 'ATA', 'ST', 81, 28),
      createPlayer('nac-12', 'Federico Santander', 'ATA', 'ST', 77, 33)
    ],
    lineup: ['nac-1', 'nac-4', 'nac-2', 'nac-3', 'nac-5', 'nac-6', 'nac-7', 'nac-8', 'nac-9', 'nac-11', 'nac-10'],
    formation: '4-3-3',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 84,
    division: 1, stadiumCapacity: 34000, stadiumName: 'Gran Parque Central', socioCount: 60000
  },
  {
    id: 'ldu-quito',
    name: 'LDU Quito',
    shortName: 'LDU',
    city: 'Quito',
    logoColor1: 'from-white',
    logoColor2: 'to-red-600',
    logoUrl: '/logos/ldu.svg',
    attack: 83,
    defense: 83,
    roster: [
      createPlayer('ldu-1', 'Alexander Domínguez', 'GOL', 'GK', 81, 37),
      createPlayer('ldu-2', 'Ricardo Adé', 'ZAG', 'CB', 82, 34),
      createPlayer('ldu-3', 'Richard Mina', 'ZAG', 'CB', 78, 25),
      createPlayer('ldu-4', 'José Quintero', 'LAT', 'RB', 80, 34),
      createPlayer('ldu-5', 'Leonel Quiñónez', 'LAT', 'LB', 78, 30, 'LEFT'),
      createPlayer('ldu-6', 'Ezequiel Piovi', 'VOL', 'DM', 82, 31),
      createPlayer('ldu-7', 'Lucas Cornejo', 'MEI', 'CM', 76, 20),
      createPlayer('ldu-8', 'Jhojan Julio', 'MEI', 'AM', 81, 26),
      createPlayer('ldu-9', 'Lisandro Alzugaray', 'ATA', 'RW', 80, 34, 'LEFT'),
      createPlayer('ldu-10', 'Alex Arce', 'ATA', 'ST', 84, 29),
      createPlayer('ldu-11', 'Michael Estrada', 'ATA', 'ST', 80, 28)
    ],
    lineup: ['ldu-1', 'ldu-4', 'ldu-2', 'ldu-3', 'ldu-5', 'ldu-6', 'ldu-7', 'ldu-8', 'ldu-9', 'ldu-10', 'ldu-11'],
    formation: '4-4-2',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 86,
    division: 1, stadiumCapacity: 41000, stadiumName: 'Rodrigo Paz Delgado', socioCount: 30000
  },
  {
    id: 'independiente-del-valle',
    name: 'Independiente del Valle',
    shortName: 'IDV',
    city: 'Sangolquí',
    logoColor1: 'from-blue-800',
    logoColor2: 'to-black',
    logoUrl: '/logos/idv.svg',
    attack: 83,
    defense: 82,
    roster: [
      createPlayer('idv-1', 'Moisés Ramírez', 'GOL', 'GK', 80, 23),
      createPlayer('idv-2', 'Mateo Carabajal', 'ZAG', 'CB', 80, 27),
      createPlayer('idv-3', 'Richard Schunke', 'ZAG', 'CB', 81, 32),
      createPlayer('idv-4', 'Matías Fernández', 'LAT', 'RB', 78, 29),
      createPlayer('idv-5', 'Beder Caicedo', 'LAT', 'LB', 77, 32, 'LEFT'),
      createPlayer('idv-6', 'Cristian Zabala', 'VOL', 'DM', 79, 26),
      createPlayer('idv-7', 'Jordy Alcívar', 'MEI', 'CM', 79, 25),
      createPlayer('idv-8', 'Junior Sornoza', 'MEI', 'AM', 83, 30, 'RIGHT'),
      createPlayer('idv-9', 'Renato Ibarra', 'ATA', 'RW', 80, 33),
      createPlayer('idv-10', 'Keny Arroyo', 'ATA', 'LW', 80, 18, 'LEFT'),
      createPlayer('idv-11', 'Jeison Medina', 'ATA', 'ST', 81, 29)
    ],
    lineup: ['idv-1', 'idv-4', 'idv-2', 'idv-3', 'idv-5', 'idv-6', 'idv-7', 'idv-8', 'idv-9', 'idv-11', 'idv-10'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 85,
    division: 1, stadiumCapacity: 12000, stadiumName: 'Banco Guayaquil', socioCount: 15000
  },
  {
    id: 'olimpia',
    name: 'Olimpia',
    shortName: 'OLI',
    city: 'Asunción',
    logoColor1: 'from-white',
    logoColor2: 'to-black',
    logoUrl: '/logos/olimpia.svg',
    attack: 81,
    defense: 81,
    roster: [
      createPlayer('oli-1', 'Gastón Olveira', 'GOL', 'GK', 81, 31),
      createPlayer('oli-2', 'Junior Barreto', 'ZAG', 'CB', 78, 26),
      createPlayer('oli-3', 'Manuel Capasso', 'ZAG', 'CB', 77, 28),
      createPlayer('oli-4', 'César Olmedo', 'LAT', 'RB', 76, 21),
      createPlayer('oli-5', 'Facundo Zabala', 'LAT', 'LB', 77, 25, 'LEFT'),
      createPlayer('oli-6', 'Richard Ortiz', 'VOL', 'DM', 80, 34, 'LEFT'),
      createPlayer('oli-7', 'Alex Franco', 'MEI', 'CM', 77, 23),
      createPlayer('oli-8', 'Rodney Redes', 'MEI', 'AM', 78, 24),
      createPlayer('oli-9', 'Derlis González', 'ATA', 'LW', 81, 30),
      createPlayer('oli-10', 'Lucas Pratto', 'ATA', 'ST', 79, 36),
      createPlayer('oli-11', 'Hugo Adrián Benítez', 'ATA', 'ST', 76, 25)
    ],
    lineup: ['oli-1', 'oli-4', 'oli-2', 'oli-3', 'oli-5', 'oli-6', 'oli-7', 'oli-8', 'oli-9', 'oli-10', 'oli-11'],
    formation: '4-4-2',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 82,
    division: 1, stadiumCapacity: 22000, stadiumName: 'Manuel Ferreira', socioCount: 30000
  },
  {
    id: 'colo-colo',
    name: 'Colo-Colo',
    shortName: 'COL',
    city: 'Santiago',
    logoColor1: 'from-white',
    logoColor2: 'to-black',
    logoUrl: '/logos/colocolo.svg',
    attack: 82,
    defense: 81,
    roster: [
      createPlayer('col-1', 'Brayan Cortés', 'GOL', 'GK', 81, 29),
      createPlayer('col-2', 'Maximilliano Falcón', 'ZAG', 'CB', 80, 27),
      createPlayer('col-3', 'Alan Saldivia', 'ZAG', 'CB', 78, 22),
      createPlayer('col-4', 'Oscar Opazo', 'LAT', 'RB', 77, 33),
      createPlayer('col-5', 'Erick Wiemberg', 'LAT', 'LB', 77, 29, 'LEFT'),
      createPlayer('col-6', 'Esteban Pavez', 'VOL', 'DM', 79, 34),
      createPlayer('col-7', 'Arturo Vidal', 'MEI', 'CM', 83, 37),
      createPlayer('col-8', 'Leonardo Gil', 'MEI', 'CM', 79, 33, 'LEFT'),
      createPlayer('col-9', 'Carlos Palacios', 'MEI', 'AM', 82, 24),
      createPlayer('col-10', 'Javier Correa', 'ATA', 'ST', 80, 31),
      createPlayer('col-11', 'Lucas Cepeda', 'ATA', 'LW', 79, 21, 'LEFT')
    ],
    lineup: ['col-1', 'col-4', 'col-2', 'col-3', 'col-5', 'col-6', 'col-7', 'col-9', 'col-11', 'col-10', 'col-8'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 84,
    division: 1, stadiumCapacity: 47000, stadiumName: 'Monumental David Arellano', socioCount: 50000
  },
  // ===== Argentina =====
  {
    id: 'racing-club',
    name: 'Racing Club',
    shortName: 'RAC',
    city: 'Avellaneda',
    logoColor1: 'from-sky-400',
    logoColor2: 'to-white',
    attack: 83,
    defense: 82,
    roster: [
      createPlayer('rac-1', 'Gabriel Arias', 'GOL', 'GK', 80, 33),
      createPlayer('rac-2', 'Marco Di Cesare', 'ZAG', 'CB', 78, 26),
      createPlayer('rac-3', 'Agustín García Basso', 'ZAG', 'CB', 77, 29),
      createPlayer('rac-4', 'Gastón Martirena', 'LAT', 'RB', 78, 33),
      createPlayer('rac-5', 'Nazareno Colombo', 'LAT', 'LB', 76, 22, 'LEFT'),
      createPlayer('rac-6', 'Bruno Zuculini', 'VOL', 'DM', 79, 31),
      createPlayer('rac-7', 'Marcelo Herrera', 'VOL', 'DM', 76, 28),
      createPlayer('rac-8', 'Juan Nardoni', 'MEI', 'CM', 79, 25),
      createPlayer('rac-9', 'Adrián Martínez', 'MEI', 'AM', 82, 25),
      createPlayer('rac-10', 'Baltasar Rodríguez', 'ATA', 'RW', 78, 22),
      createPlayer('rac-11', 'Maximiliano Salas', 'ATA', 'ST', 82, 26)
    ],
    lineup: ['rac-1', 'rac-4', 'rac-2', 'rac-3', 'rac-5', 'rac-6', 'rac-7', 'rac-8', 'rac-9', 'rac-10', 'rac-11'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 83,
    division: 1, stadiumCapacity: 50000, stadiumName: 'Presidente Perón', socioCount: 100000
  },
  {
    id: 'independiente-avellaneda',
    name: 'Independiente',
    shortName: 'IND',
    city: 'Avellaneda',
    logoColor1: 'from-red-600',
    logoColor2: 'to-red-900',
    attack: 79,
    defense: 78,
    roster: [
      createPlayer('ind-1', 'Rodrigo Rey', 'GOL', 'GK', 77, 34),
      createPlayer('ind-2', 'Gastón Verón', 'ZAG', 'CB', 76, 26),
      createPlayer('ind-3', 'Kevin Lomónaco', 'ZAG', 'CB', 78, 22),
      createPlayer('ind-4', 'Federico Vera', 'LAT', 'RB', 75, 24),
      createPlayer('ind-5', 'Gabriel Ávalos', 'ATA', 'ST', 78, 30),
      createPlayer('ind-6', 'Alan Soñora', 'VOL', 'DM', 76, 24),
      createPlayer('ind-7', 'Iván Marcone', 'VOL', 'DM', 77, 33),
      createPlayer('ind-8', 'Matías Giménez', 'MEI', 'CM', 75, 23),
      createPlayer('ind-9', 'Braian Martínez', 'MEI', 'AM', 76, 25),
      createPlayer('ind-10', 'Santiago Maratea', 'ATA', 'LW', 74, 21, 'LEFT'),
      createPlayer('ind-11', 'Gonzalo Verón', 'ATA', 'RW', 78, 29)
    ],
    lineup: ['ind-1', 'ind-4', 'ind-2', 'ind-3', 'ind-6', 'ind-7', 'ind-8', 'ind-9', 'ind-11', 'ind-5', 'ind-10'],
    formation: '4-2-3-1',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 79,
    division: 1, stadiumCapacity: 48000, stadiumName: 'Libertadores de América', socioCount: 90000
  },
  {
    id: 'san-lorenzo',
    name: 'San Lorenzo',
    shortName: 'SLO',
    city: 'Buenos Aires',
    logoColor1: 'from-blue-700',
    logoColor2: 'to-red-600',
    attack: 78,
    defense: 77,
    roster: [
      createPlayer('slo-1', 'Facundo Altamirano', 'GOL', 'GK', 76, 26),
      createPlayer('slo-2', 'Gastón Hernández', 'ZAG', 'CB', 75, 28),
      createPlayer('slo-3', 'Rodrigo Herrera', 'ZAG', 'CB', 76, 30),
      createPlayer('slo-4', 'Fabricio Domínguez', 'LAT', 'RB', 74, 23),
      createPlayer('slo-5', 'Nicolás Reniero', 'ATA', 'ST', 77, 27),
      createPlayer('slo-6', 'Elián Irala', 'LAT', 'LB', 74, 24, 'LEFT'),
      createPlayer('slo-7', 'Alexis Cuello', 'MEI', 'AM', 78, 26),
      createPlayer('slo-8', 'Iker Muniain', 'MEI', 'CM', 76, 29, 'LEFT'),
      createPlayer('slo-9', 'Adam Bareiro', 'ATA', 'ST', 77, 27),
      createPlayer('slo-10', 'Máximo Perrone', 'VOL', 'DM', 75, 22),
      createPlayer('slo-11', 'Agustín Giay', 'LAT', 'RB', 76, 22)
    ],
    lineup: ['slo-1', 'slo-4', 'slo-2', 'slo-3', 'slo-6', 'slo-10', 'slo-8', 'slo-7', 'slo-9', 'slo-5', 'slo-11'],
    formation: '4-4-2',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 77,
    division: 1, stadiumCapacity: 47000, stadiumName: 'Pedro Bidegain', socioCount: 40000
  },
  {
    id: 'velez-sarsfield',
    name: 'Vélez Sarsfield',
    shortName: 'VEL',
    city: 'Buenos Aires',
    logoColor1: 'from-white',
    logoColor2: 'to-blue-600',
    attack: 80,
    defense: 80,
    roster: [
      createPlayer('vel-1', 'Tomás Marchiori', 'GOL', 'GK', 78, 25),
      createPlayer('vel-2', 'Lautaro Gianetti', 'ZAG', 'CB', 78, 26),
      createPlayer('vel-3', 'Julián Fernández', 'ZAG', 'CB', 76, 23),
      createPlayer('vel-4', 'Emanuel Mammana', 'ZAG', 'CB', 77, 29),
      createPlayer('vel-5', 'Marcelo Saracchi', 'LAT', 'LB', 78, 27, 'LEFT'),
      createPlayer('vel-6', 'Nicolás Garayalde', 'VOL', 'DM', 76, 26),
      createPlayer('vel-7', 'Gastón González', 'MEI', 'CM', 77, 24),
      createPlayer('vel-8', 'Manuel Lanzini', 'MEI', 'AM', 79, 31),
      createPlayer('vel-9', 'Braian Romero', 'ATA', 'ST', 80, 30),
      createPlayer('vel-10', 'Maher Carrizo', 'MEI', 'AM', 79, 20),
      createPlayer('vel-11', 'Rodrigo Aliendro', 'VOL', 'DM', 77, 30)
    ],
    lineup: ['vel-1', 'vel-2', 'vel-3', 'vel-4', 'vel-5', 'vel-6', 'vel-11', 'vel-8', 'vel-10', 'vel-9', 'vel-7'],
    formation: '4-3-3',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 80,
    division: 1, stadiumCapacity: 49000, stadiumName: 'José Amalfitani', socioCount: 45000
  },
  {
    id: 'talleres-cordoba',
    name: 'Talleres',
    shortName: 'TAL',
    city: 'Córdoba',
    logoColor1: 'from-blue-600',
    logoColor2: 'to-red-500',
    attack: 79,
    defense: 79,
    roster: [
      createPlayer('tal-1', 'Guido Herrera', 'GOL', 'GK', 78, 34),
      createPlayer('tal-2', 'Juan Portillo', 'ZAG', 'CB', 76, 30),
      createPlayer('tal-3', 'Federico Vera', 'ZAG', 'CB', 76, 27),
      createPlayer('tal-4', 'Rodrigo Garro', 'MEI', 'AM', 80, 27, 'LEFT'),
      createPlayer('tal-5', 'Ángel Correa', 'ATA', 'RW', 82, 30),
      createPlayer('tal-6', 'Nicolás Fernández', 'LAT', 'RB', 75, 25),
      createPlayer('tal-7', 'Bruno Amione', 'ZAG', 'CB', 77, 24),
      createPlayer('tal-8', 'Ramiro Carrera', 'MEI', 'CM', 76, 26),
      createPlayer('tal-9', 'Nicolás Comachi', 'ATA', 'ST', 76, 23),
      createPlayer('tal-10', 'Tomás Pochettino', 'VOL', 'DM', 75, 25),
      createPlayer('tal-11', 'Bruno Zapelli', 'MEI', 'AM', 78, 26)
    ],
    lineup: ['tal-1', 'tal-6', 'tal-2', 'tal-3', 'tal-7', 'tal-10', 'tal-8', 'tal-11', 'tal-5', 'tal-9', 'tal-4'],
    formation: '4-4-2',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 80,
    division: 1, stadiumCapacity: 57000, stadiumName: 'Mario Alberto Kempes', socioCount: 40000
  },
  {
    id: 'estudiantes-la-plata',
    name: 'Estudiantes de La Plata',
    shortName: 'EDLP',
    city: 'La Plata',
    logoColor1: 'from-red-700',
    logoColor2: 'to-white',
    attack: 79,
    defense: 80,
    roster: [
      createPlayer('edlp-1', 'Mariano Andújar', 'GOL', 'GK', 78, 39),
      createPlayer('edlp-2', 'Santiago Núñez', 'ZAG', 'CB', 78, 24),
      createPlayer('edlp-3', 'Fernando Zuqui', 'VOL', 'DM', 77, 33),
      createPlayer('edlp-4', 'Gastón Benedetti', 'MEI', 'CM', 76, 27),
      createPlayer('edlp-5', 'Mauro Méndez', 'ATA', 'LW', 77, 25, 'LEFT'),
      createPlayer('edlp-6', 'Franco Zapiola', 'ATA', 'ST', 78, 24),
      createPlayer('edlp-7', 'Cristian Medina', 'MEI', 'AM', 78, 23),
      createPlayer('edlp-8', 'Ignacio Rodríguez', 'LAT', 'RB', 75, 23),
      createPlayer('edlp-9', 'Enzo Roldán', 'LAT', 'LB', 74, 22, 'LEFT'),
      createPlayer('edlp-10', 'Javier Correa', 'ATA', 'ST', 79, 32),
      createPlayer('edlp-11', 'Guillermo Pol Fernández', 'VOL', 'DM', 77, 32)
    ],
    lineup: ['edlp-1', 'edlp-8', 'edlp-2', 'edlp-9', 'edlp-3', 'edlp-11', 'edlp-4', 'edlp-7', 'edlp-5', 'edlp-10', 'edlp-6'],
    formation: '4-1-4-1',
    style: 'Defensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 79,
    division: 1, stadiumCapacity: 35000, stadiumName: 'Jorge Luis Hirschi', socioCount: 35000
  },
  // ===== Uruguay =====
  {
    id: 'defensor-sporting',
    name: 'Defensor Sporting',
    shortName: 'DEF',
    city: 'Montevideo',
    logoColor1: 'from-violet-700',
    logoColor2: 'to-white',
    attack: 76,
    defense: 76,
    roster: [
      createPlayer('def-1', 'Rodrigo Rey', 'GOL', 'GK', 75, 27),
      createPlayer('def-2', 'Bruno Pittón', 'ZAG', 'CB', 74, 24),
      createPlayer('def-3', 'Emiliano Cristaldo', 'ZAG', 'CB', 74, 26),
      createPlayer('def-4', 'Nicolás Cabrera', 'LAT', 'RB', 73, 23),
      createPlayer('def-5', 'Sebastián Cristóforo', 'VOL', 'DM', 76, 33),
      createPlayer('def-6', 'Facundo Labandeira', 'LAT', 'LB', 73, 24, 'LEFT'),
      createPlayer('def-7', 'Emanuel Gularte', 'MEI', 'CM', 75, 27),
      createPlayer('def-8', 'Nicolás Acevedo', 'VOL', 'DM', 76, 27),
      createPlayer('def-9', 'Franco Nicola', 'ATA', 'RW', 76, 24),
      createPlayer('def-10', 'Kevin Ramírez', 'ATA', 'ST', 77, 26),
      createPlayer('def-11', 'Emiliano Hernández', 'MEI', 'AM', 75, 25)
    ],
    lineup: ['def-1', 'def-4', 'def-2', 'def-3', 'def-6', 'def-5', 'def-8', 'def-7', 'def-9', 'def-10', 'def-11'],
    formation: '4-3-3',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 76,
    division: 1, stadiumCapacity: 16000, stadiumName: 'Luis Franzini', socioCount: 12000
  },
  // ===== Paraguay =====
  {
    id: 'cerro-porteno',
    name: 'Cerro Porteño',
    shortName: 'CER',
    city: 'Asunción',
    logoColor1: 'from-blue-700',
    logoColor2: 'to-red-600',
    attack: 79,
    defense: 78,
    roster: [
      createPlayer('cer-1', 'Jean Fernandes', 'GOL', 'GK', 78, 30),
      createPlayer('cer-2', 'Fabián Balbuena', 'ZAG', 'CB', 79, 33),
      createPlayer('cer-3', 'Alan Rodríguez', 'ZAG', 'CB', 76, 25),
      createPlayer('cer-4', 'Marcelo Palau', 'LAT', 'RB', 75, 26),
      createPlayer('cer-5', 'Ramón Sosa', 'ATA', 'LW', 79, 25, 'LEFT'),
      createPlayer('cer-6', 'Óscar Cardozo', 'ATA', 'ST', 76, 40),
      createPlayer('cer-7', 'Rodrigo Rojas', 'LAT', 'LB', 74, 24, 'LEFT'),
      createPlayer('cer-8', 'Juan Patiño', 'VOL', 'DM', 76, 25),
      createPlayer('cer-9', 'Adonis Frutos', 'VOL', 'DM', 75, 24),
      createPlayer('cer-10', 'Iván Torres', 'MEI', 'AM', 77, 25),
      createPlayer('cer-11', 'Diego Duarte', 'ATA', 'ST', 78, 27)
    ],
    lineup: ['cer-1', 'cer-4', 'cer-2', 'cer-3', 'cer-7', 'cer-8', 'cer-9', 'cer-10', 'cer-5', 'cer-11', 'cer-6'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 79,
    division: 1, stadiumCapacity: 44000, stadiumName: 'General Pablo Rojas', socioCount: 50000
  },
  {
    id: 'libertad-py',
    name: 'Libertad',
    shortName: 'LIB',
    city: 'Asunción',
    logoColor1: 'from-neutral-900',
    logoColor2: 'to-white',
    attack: 76,
    defense: 77,
    roster: [
      createPlayer('lib-1', 'Marcos Miers', 'GOL', 'GK', 75, 28),
      createPlayer('lib-2', 'Omar Alderete', 'ZAG', 'CB', 78, 28),
      createPlayer('lib-3', 'Matías Espinoza', 'ZAG', 'CB', 75, 26),
      createPlayer('lib-4', 'Fabián Ferreira', 'VOL', 'DM', 76, 28),
      createPlayer('lib-5', 'Antonio Galeano', 'ATA', 'RW', 76, 25),
      createPlayer('lib-6', 'Sergio Díaz', 'ATA', 'ST', 77, 29),
      createPlayer('lib-7', 'Claudio Aquino', 'MEI', 'AM', 77, 32),
      createPlayer('lib-8', 'Rodrigo Bogado', 'LAT', 'RB', 74, 24),
      createPlayer('lib-9', 'Gustavo Caballero', 'LAT', 'LB', 74, 25, 'LEFT'),
      createPlayer('lib-10', 'Iván Franco', 'VOL', 'DM', 75, 26),
      createPlayer('lib-11', 'Rodrigo Sanabria', 'MEI', 'CM', 75, 24)
    ],
    lineup: ['lib-1', 'lib-8', 'lib-2', 'lib-3', 'lib-9', 'lib-4', 'lib-10', 'lib-11', 'lib-7', 'lib-5', 'lib-6'],
    formation: '4-3-3',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 77,
    division: 1, stadiumCapacity: 14000, stadiumName: 'Dr. Nicolás Leoz', socioCount: 20000
  },
  // ===== Chile =====
  {
    id: 'universidad-de-chile',
    name: 'Universidad de Chile',
    shortName: 'UCH',
    city: 'Santiago',
    logoColor1: 'from-blue-700',
    logoColor2: 'to-neutral-900',
    attack: 80,
    defense: 79,
    roster: [
      createPlayer('uch-1', 'Cristopher Toselli', 'GOL', 'GK', 79, 34),
      createPlayer('uch-2', 'Franco Calderón', 'ZAG', 'CB', 77, 27),
      createPlayer('uch-3', 'Matías Zaldivia', 'ZAG', 'CB', 76, 33),
      createPlayer('uch-4', 'Nicolás Ramírez', 'LAT', 'RB', 75, 22),
      createPlayer('uch-5', 'Franco Lobos', 'LAT', 'LB', 74, 24, 'LEFT'),
      createPlayer('uch-6', 'Israel Poblete', 'VOL', 'DM', 77, 26),
      createPlayer('uch-7', 'Rodrigo Contreras', 'MEI', 'CM', 76, 25),
      createPlayer('uch-8', 'Lucas Assadi', 'MEI', 'AM', 79, 20),
      createPlayer('uch-9', 'Leandro Fernández', 'ATA', 'ST', 79, 26),
      createPlayer('uch-10', 'Cristián Palacios', 'ATA', 'LW', 78, 30, 'LEFT'),
      createPlayer('uch-11', 'Marcelo Díaz', 'VOL', 'DM', 77, 38)
    ],
    lineup: ['uch-1', 'uch-4', 'uch-2', 'uch-3', 'uch-5', 'uch-11', 'uch-6', 'uch-8', 'uch-10', 'uch-9', 'uch-7'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 80,
    division: 1, stadiumCapacity: 47000, stadiumName: 'Estadio Nacional', socioCount: 40000
  },
  {
    id: 'universidad-catolica',
    name: 'Universidad Católica',
    shortName: 'UC',
    city: 'Santiago',
    logoColor1: 'from-white',
    logoColor2: 'to-purple-800',
    attack: 79,
    defense: 80,
    roster: [
      createPlayer('uc-1', 'Diego Sánchez', 'GOL', 'GK', 78, 27),
      createPlayer('uc-2', 'Gonzalo Tapia', 'ATA', 'ST', 78, 26),
      createPlayer('uc-3', 'Branco Ampuero', 'ZAG', 'CB', 76, 22),
      createPlayer('uc-4', 'Eugenio Mena', 'LAT', 'LB', 77, 35, 'LEFT'),
      createPlayer('uc-5', 'Alfred Canales', 'LAT', 'RB', 74, 24),
      createPlayer('uc-6', 'Vicente Pizarro', 'VOL', 'DM', 78, 22),
      createPlayer('uc-7', 'Fernando Zampedri', 'ATA', 'ST', 80, 35),
      createPlayer('uc-8', 'Diego Valencia', 'ATA', 'RW', 78, 27),
      createPlayer('uc-9', 'Marcelino Núñez', 'MEI', 'CM', 78, 25),
      createPlayer('uc-10', 'Cristián Cuevas', 'MEI', 'AM', 76, 27),
      createPlayer('uc-11', 'Matías Zaldivia', 'ZAG', 'CB', 76, 33)
    ],
    lineup: ['uc-1', 'uc-5', 'uc-3', 'uc-11', 'uc-4', 'uc-6', 'uc-9', 'uc-10', 'uc-8', 'uc-2', 'uc-7'],
    formation: '4-3-3',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 79,
    division: 1, stadiumCapacity: 20000, stadiumName: 'San Carlos de Apoquindo', socioCount: 25000
  },
  // ===== Ecuador =====
  {
    id: 'barcelona-sc',
    name: 'Barcelona SC',
    shortName: 'BSC',
    city: 'Guayaquil',
    logoColor1: 'from-yellow-400',
    logoColor2: 'to-neutral-900',
    attack: 81,
    defense: 80,
    roster: [
      createPlayer('bsc-1', 'Javier Burrai', 'GOL', 'GK', 79, 27),
      createPlayer('bsc-2', 'Joao Rojas', 'ATA', 'RW', 78, 32),
      createPlayer('bsc-3', 'Mario Pineida', 'LAT', 'LB', 78, 30, 'LEFT'),
      createPlayer('bsc-4', 'Fidel Martínez', 'ATA', 'LW', 79, 32, 'LEFT'),
      createPlayer('bsc-5', 'Damián Díaz', 'MEI', 'AM', 79, 33, 'LEFT'),
      createPlayer('bsc-6', 'Michael Carcelén', 'LAT', 'RB', 76, 26),
      createPlayer('bsc-7', 'Jhojan Julio', 'MEI', 'CM', 77, 26),
      createPlayer('bsc-8', 'Gabriel Cortez', 'ATA', 'ST', 79, 27),
      createPlayer('bsc-9', 'Ramón Ábila', 'ATA', 'ST', 78, 34),
      createPlayer('bsc-10', 'Xavier Arreaga', 'ZAG', 'CB', 79, 30),
      createPlayer('bsc-11', 'Alan Franco', 'VOL', 'DM', 78, 27)
    ],
    lineup: ['bsc-1', 'bsc-6', 'bsc-10', 'bsc-3', 'bsc-11', 'bsc-7', 'bsc-5', 'bsc-2', 'bsc-4', 'bsc-8', 'bsc-9'],
    formation: '4-1-4-1',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 81,
    division: 1, stadiumCapacity: 57000, stadiumName: 'Monumental Banco Pichincha', socioCount: 60000
  },
  {
    id: 'emelec',
    name: 'Emelec',
    shortName: 'EME',
    city: 'Guayaquil',
    logoColor1: 'from-blue-600',
    logoColor2: 'to-white',
    attack: 78,
    defense: 78,
    roster: [
      createPlayer('eme-1', 'Damián Lanza', 'GOL', 'GK', 77, 29),
      createPlayer('eme-2', 'Ricardo Adé', 'ZAG', 'CB', 78, 34),
      createPlayer('eme-3', 'Jhon Espinoza', 'ZAG', 'CB', 75, 25),
      createPlayer('eme-4', 'Bryan Carabalí', 'LAT', 'RB', 74, 24),
      createPlayer('eme-5', 'Gonzalo Mastriani', 'ATA', 'ST', 78, 30),
      createPlayer('eme-6', 'Bryan Angulo', 'ATA', 'ST', 77, 33),
      createPlayer('eme-7', 'Miller Bolaños', 'ATA', 'LW', 77, 32, 'LEFT'),
      createPlayer('eme-8', 'Fidel Martínez', 'MEI', 'AM', 76, 32),
      createPlayer('eme-9', 'Anthony Landázuri', 'LAT', 'LB', 73, 22, 'LEFT'),
      createPlayer('eme-10', 'Jorge Guagua', 'VOL', 'DM', 76, 35),
      createPlayer('eme-11', 'Adonis Preciado', 'MEI', 'CM', 75, 24)
    ],
    lineup: ['eme-1', 'eme-4', 'eme-2', 'eme-3', 'eme-9', 'eme-10', 'eme-11', 'eme-8', 'eme-7', 'eme-5', 'eme-6'],
    formation: '4-3-3',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 78,
    division: 1, stadiumCapacity: 20000, stadiumName: 'Banco Pichincha (Capwell)', socioCount: 30000
  },
  // ===== Colômbia =====
  {
    id: 'atletico-nacional',
    name: 'Atlético Nacional',
    shortName: 'NAL',
    city: 'Medellín',
    logoColor1: 'from-emerald-600',
    logoColor2: 'to-white',
    attack: 81,
    defense: 80,
    roster: [
      createPlayer('nal-1', 'Kevin Mier', 'GOL', 'GK', 79, 25),
      createPlayer('nal-2', 'Andrés Andrade', 'ZAG', 'CB', 78, 27),
      createPlayer('nal-3', 'Alejandro Zuleta', 'ZAG', 'CB', 76, 24),
      createPlayer('nal-4', 'William Tesillo', 'LAT', 'LB', 77, 35, 'LEFT'),
      createPlayer('nal-5', 'Cristian Zapata', 'LAT', 'RB', 75, 24),
      createPlayer('nal-6', 'Andrés Roa', 'VOL', 'DM', 77, 33),
      createPlayer('nal-7', 'Alfredo Morelos', 'ATA', 'ST', 80, 29),
      createPlayer('nal-8', 'Jorman Campuzano', 'VOL', 'DM', 76, 29),
      createPlayer('nal-9', 'Marino Hinestroza', 'ATA', 'RW', 78, 25),
      createPlayer('nal-10', 'Édwin Cardona', 'MEI', 'AM', 79, 32),
      createPlayer('nal-11', 'Jefferson Duque', 'ATA', 'ST', 77, 34)
    ],
    lineup: ['nal-1', 'nal-5', 'nal-2', 'nal-3', 'nal-4', 'nal-6', 'nal-8', 'nal-10', 'nal-9', 'nal-7', 'nal-11'],
    formation: '4-2-3-1',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 81,
    division: 1, stadiumCapacity: 40000, stadiumName: 'Atanasio Girardot', socioCount: 45000
  },
  {
    id: 'millonarios',
    name: 'Millonarios',
    shortName: 'MIL',
    city: 'Bogotá',
    logoColor1: 'from-blue-700',
    logoColor2: 'to-white',
    attack: 79,
    defense: 78,
    roster: [
      createPlayer('mil-1', 'Álvaro Montero', 'GOL', 'GK', 80, 28),
      createPlayer('mil-2', 'Andrés Llinás', 'ZAG', 'CB', 78, 28),
      createPlayer('mil-3', 'Jhon Duque', 'ZAG', 'CB', 75, 24),
      createPlayer('mil-4', 'Juan Pablo Vargas', 'ZAG', 'CB', 77, 27),
      createPlayer('mil-5', 'Elvis Perlaza', 'LAT', 'RB', 74, 23),
      createPlayer('mil-6', 'Larry Vásquez', 'VOL', 'DM', 76, 25),
      createPlayer('mil-7', 'Daniel Ruiz', 'MEI', 'AM', 79, 24),
      createPlayer('mil-8', 'Leonardo Castro', 'ATA', 'ST', 78, 32),
      createPlayer('mil-9', 'Ómar Bertel', 'LAT', 'LB', 73, 23, 'LEFT'),
      createPlayer('mil-10', 'Radamel Falcao García', 'ATA', 'ST', 80, 39),
      createPlayer('mil-11', 'Fernando Uribe', 'ATA', 'ST', 76, 36)
    ],
    lineup: ['mil-1', 'mil-5', 'mil-2', 'mil-4', 'mil-9', 'mil-6', 'mil-3', 'mil-7', 'mil-8', 'mil-10', 'mil-11'],
    formation: '4-3-3',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 79,
    division: 1, stadiumCapacity: 36000, stadiumName: 'El Campín', socioCount: 40000
  },
  {
    id: 'junior-barranquilla',
    name: 'Junior de Barranquilla',
    shortName: 'JUN',
    city: 'Barranquilla',
    logoColor1: 'from-red-600',
    logoColor2: 'to-white',
    attack: 78,
    defense: 77,
    roster: [
      createPlayer('jun-1', 'Sebastián Viera', 'GOL', 'GK', 77, 39),
      createPlayer('jun-2', 'Jonathan Álvez', 'ZAG', 'CB', 76, 30),
      createPlayer('jun-3', 'Yesus Cabrera', 'ZAG', 'CB', 74, 25),
      createPlayer('jun-4', 'Didier Moreno', 'LAT', 'RB', 75, 34),
      createPlayer('jun-5', 'Jarlan Barrera', 'MEI', 'AM', 78, 28),
      createPlayer('jun-6', 'Carlos Bacca', 'ATA', 'ST', 79, 38),
      createPlayer('jun-7', 'Yimmi Chará', 'ATA', 'LW', 78, 31, 'LEFT'),
      createPlayer('jun-8', 'Steven Rodallega', 'LAT', 'LB', 73, 23, 'LEFT'),
      createPlayer('jun-9', 'Sherman Cárdenas', 'MEI', 'CM', 76, 26),
      createPlayer('jun-10', 'Víctor Cantillo', 'VOL', 'DM', 76, 31),
      createPlayer('jun-11', 'Bryan Castrillón', 'ATA', 'RW', 76, 25)
    ],
    lineup: ['jun-1', 'jun-4', 'jun-2', 'jun-3', 'jun-8', 'jun-10', 'jun-9', 'jun-5', 'jun-11', 'jun-6', 'jun-7'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 78,
    division: 1, stadiumCapacity: 46000, stadiumName: 'Metropolitano Roberto Meléndez', socioCount: 40000
  },
  // ===== Peru =====
  {
    id: 'universitario-per',
    name: 'Universitario de Deportes',
    shortName: 'UNI',
    city: 'Lima',
    logoColor1: 'from-neutral-100',
    logoColor2: 'to-red-700',
    attack: 79,
    defense: 78,
    roster: [
      createPlayer('uni-1', 'Sebastián Britos', 'GOL', 'GK', 77, 25),
      createPlayer('uni-2', 'Aldo Corzo', 'LAT', 'RB', 76, 34),
      createPlayer('uni-3', 'Anthony Osorio', 'ZAG', 'CB', 75, 24),
      createPlayer('uni-4', 'Riquelme Rodríguez', 'ZAG', 'CB', 76, 26),
      createPlayer('uni-5', 'Jesús Castillo', 'VOL', 'DM', 78, 26),
      createPlayer('uni-6', 'Alex Valera', 'ATA', 'ST', 80, 28),
      createPlayer('uni-7', 'Edison Flores', 'MEI', 'AM', 78, 31),
      createPlayer('uni-8', 'Rodrigo Ureña', 'VOL', 'DM', 77, 32),
      createPlayer('uni-9', 'Andy Polo', 'LAT', 'LB', 76, 32, 'LEFT'),
      createPlayer('uni-10', 'Jairo Vélez', 'ATA', 'RW', 76, 24),
      createPlayer('uni-11', 'Jairo Concha', 'MEI', 'CM', 76, 26)
    ],
    lineup: ['uni-1', 'uni-2', 'uni-3', 'uni-4', 'uni-9', 'uni-5', 'uni-8', 'uni-11', 'uni-7', 'uni-10', 'uni-6'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 80,
    division: 1, stadiumCapacity: 80000, stadiumName: 'Monumental U', socioCount: 90000
  },
  {
    id: 'alianza-lima',
    name: 'Alianza Lima',
    shortName: 'ALI',
    city: 'Lima',
    logoColor1: 'from-blue-700',
    logoColor2: 'to-white',
    attack: 78,
    defense: 77,
    roster: [
      createPlayer('ali-1', 'Ángelo Campos', 'GOL', 'GK', 77, 28),
      createPlayer('ali-2', 'Carlos Zambrano', 'ZAG', 'CB', 78, 34),
      createPlayer('ali-3', 'Renzo Garcés', 'ZAG', 'CB', 75, 27),
      createPlayer('ali-4', 'Marco Huamán', 'LAT', 'RB', 74, 25),
      createPlayer('ali-5', 'Yordi Vílchez', 'LAT', 'LB', 74, 26, 'LEFT'),
      createPlayer('ali-6', 'Pablo Ceppelini', 'MEI', 'AM', 78, 30, 'LEFT'),
      createPlayer('ali-7', 'Jesús Castillo', 'VOL', 'DM', 76, 26),
      createPlayer('ali-8', 'Hernán Barcos', 'ATA', 'ST', 78, 40),
      createPlayer('ali-9', 'Pablo Sabbag', 'ATA', 'ST', 77, 26),
      createPlayer('ali-10', 'Jairo Concha', 'MEI', 'CM', 76, 26),
      createPlayer('ali-11', 'Guillermo Enrique', 'LAT', 'RB', 74, 24)
    ],
    lineup: ['ali-1', 'ali-4', 'ali-2', 'ali-3', 'ali-5', 'ali-7', 'ali-10', 'ali-6', 'ali-9', 'ali-8', 'ali-11'],
    formation: '4-4-2',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 78,
    division: 1, stadiumCapacity: 35000, stadiumName: 'Alejandro Villanueva', socioCount: 45000
  },
  // ===== Bolívia =====
  {
    id: 'bolivar',
    name: 'Bolívar',
    shortName: 'BOL',
    city: 'La Paz',
    logoColor1: 'from-sky-400',
    logoColor2: 'to-white',
    attack: 77,
    defense: 76,
    roster: [
      createPlayer('bol-1', 'Guillermo Viscarra', 'GOL', 'GK', 77, 30),
      createPlayer('bol-2', 'Diego Wayar', 'ZAG', 'CB', 75, 27),
      createPlayer('bol-3', 'Adrián Jusino', 'ZAG', 'CB', 74, 30),
      createPlayer('bol-4', 'José Sagredo', 'LAT', 'RB', 73, 25),
      createPlayer('bol-5', 'Erwin Saavedra', 'ATA', 'RW', 76, 26),
      createPlayer('bol-6', 'Boris Céspedes', 'LAT', 'LB', 73, 26, 'LEFT'),
      createPlayer('bol-7', 'Gustavo Ovando', 'VOL', 'DM', 75, 27),
      createPlayer('bol-8', 'Robert Toro', 'MEI', 'CM', 74, 25),
      createPlayer('bol-9', 'Bruno Miranda', 'MEI', 'AM', 76, 24),
      createPlayer('bol-10', 'Carmelo Algarañaz', 'ATA', 'LW', 77, 23, 'LEFT'),
      createPlayer('bol-11', 'Gilbert Álvarez', 'ATA', 'ST', 76, 29)
    ],
    lineup: ['bol-1', 'bol-4', 'bol-2', 'bol-3', 'bol-6', 'bol-7', 'bol-8', 'bol-9', 'bol-5', 'bol-11', 'bol-10'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 77,
    division: 1, stadiumCapacity: 41000, stadiumName: 'Hernando Siles', socioCount: 30000
  },
  {
    id: 'the-strongest',
    name: 'The Strongest',
    shortName: 'TST',
    city: 'La Paz',
    logoColor1: 'from-yellow-400',
    logoColor2: 'to-neutral-900',
    attack: 76,
    defense: 76,
    roster: [
      createPlayer('tst-1', 'Javier Rojas', 'GOL', 'GK', 75, 28),
      createPlayer('tst-2', 'Marvin Bejarano', 'ZAG', 'CB', 74, 26),
      createPlayer('tst-3', 'Erick Pettersen', 'ZAG', 'CB', 75, 27),
      createPlayer('tst-4', 'Diego Bejarano', 'LAT', 'RB', 73, 25),
      createPlayer('tst-5', 'Martín Prost', 'VOL', 'DM', 74, 26),
      createPlayer('tst-6', 'Gonzalo Almirón', 'LAT', 'LB', 73, 27, 'LEFT'),
      createPlayer('tst-7', 'Damián Vera', 'MEI', 'CM', 75, 24),
      createPlayer('tst-8', 'Alexander Meleán', 'MEI', 'AM', 76, 26),
      createPlayer('tst-9', 'Miguel Ángel Zeballos', 'ATA', 'RW', 76, 23),
      createPlayer('tst-10', 'Marcelo Suárez', 'ATA', 'ST', 77, 27),
      createPlayer('tst-11', 'Enzo Monteiro', 'ATA', 'ST', 75, 24)
    ],
    lineup: ['tst-1', 'tst-4', 'tst-2', 'tst-3', 'tst-6', 'tst-5', 'tst-7', 'tst-8', 'tst-9', 'tst-10', 'tst-11'],
    formation: '4-3-3',
    style: 'Equilibrado',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 76,
    division: 1, stadiumCapacity: 41000, stadiumName: 'Hernando Siles', socioCount: 25000
  },
  // ===== Venezuela =====
  {
    id: 'deportivo-tachira',
    name: 'Deportivo Táchira',
    shortName: 'TAC',
    city: 'San Cristóbal',
    logoColor1: 'from-red-800',
    logoColor2: 'to-white',
    attack: 75,
    defense: 75,
    roster: [
      createPlayer('tac-1', 'Rafael Romo', 'GOL', 'GK', 75, 33),
      createPlayer('tac-2', 'Yordan Osorio', 'ZAG', 'CB', 76, 27),
      createPlayer('tac-3', 'Jhon Chancellor', 'ZAG', 'CB', 74, 34),
      createPlayer('tac-4', 'Ronaldo Peña', 'LAT', 'RB', 72, 24),
      createPlayer('tac-5', 'Jefferson Savarino', 'ATA', 'RW', 78, 30),
      createPlayer('tac-6', 'Richard Celis', 'LAT', 'LB', 72, 23, 'LEFT'),
      createPlayer('tac-7', 'Yeferson Soteldo', 'ATA', 'LW', 78, 28, 'LEFT'),
      createPlayer('tac-8', 'Junior Moreno', 'VOL', 'DM', 75, 31),
      createPlayer('tac-9', 'Jan Hurtado', 'ATA', 'ST', 76, 26),
      createPlayer('tac-10', 'Cristian Cásseres Jr.', 'MEI', 'CM', 76, 27),
      createPlayer('tac-11', 'Nahuel Ferraresi', 'ZAG', 'CB', 76, 28)
    ],
    lineup: ['tac-1', 'tac-4', 'tac-2', 'tac-11', 'tac-6', 'tac-8', 'tac-10', 'tac-7', 'tac-5', 'tac-9', 'tac-3'],
    formation: '4-3-3',
    style: 'Ofensivo',
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0, moral: 75,
    division: 1, stadiumCapacity: 35000, stadiumName: 'Pueblo Nuevo', socioCount: 20000
  }
];

SOUTH_AMERICAN_FOREIGN_CLUBS.forEach(team => {
  const importedRoster = createSouthAmericanRoster(team.id, Math.round((team.attack + team.defense) / 2));
  if (importedRoster.length === 0) return;
  team.roster = importedRoster;
  team.lineup = selectBestLineupForFormation(importedRoster, team.formation);
});
