
import { Player, Team, WCTeamData, WCConfederation, DetailedPosition } from './types';

// ========== GERADOR DE JOGADOR NACIONAL ==========

export const DETAILED_POS_MAP: Record<string, DetailedPosition[]> = {
  'GOL': ['GK'],
  'ZAG': ['CB'],
  'LAT': ['RB', 'LB'],
  'VOL': ['DM'],
  'MEI': ['CM', 'AM'],
  'ATA': ['ST', 'RW', 'LW']
};

const generateStats = (detPos: DetailedPosition, ovr: number, age: number) => {
  const r = (base: number) => Math.min(99, Math.max(10, Math.round(base) + Math.floor(Math.random() * 12) - 6));
  
  const stats = {
    pace: r(ovr), shooting: r(ovr * 0.7), passing: r(ovr * 0.7), dribbling: r(ovr * 0.7), 
    defending: r(ovr * 0.6), physical: r(ovr * 0.75), keeping: 10,
    crossing: r(ovr * 0.6), finishing: r(ovr * 0.6), tackling: r(ovr * 0.6), 
    marking: r(ovr * 0.6), positioning: r(ovr * 0.7), strength: r(ovr * 0.7), 
    stamina: r(ovr * 0.75), vision: r(ovr * 0.6), longShot: r(ovr * 0.5), 
    heading: r(ovr * 0.5), reflexes: 10, handling: 10
  };

  if (detPos === 'GK') {
    stats.keeping = r(ovr);
    stats.reflexes = r(ovr * 1.1);
    stats.handling = r(ovr * 0.9);
  } else if (['CB', 'DM'].includes(detPos)) {
    stats.defending = r(ovr);
    stats.marking = r(ovr * 0.95);
    stats.tackling = r(ovr * 0.9);
  } else if (['RB', 'LB'].includes(detPos)) {
    stats.pace = r(ovr * 0.9);
    stats.crossing = r(ovr * 0.85);
  } else if (['ST', 'LW', 'RW'].includes(detPos)) {
    stats.finishing = r(ovr * 0.95);
    stats.shooting = r(ovr);
  }

  if (age > 31) { stats.pace -= 8; stats.positioning += 5; }
  return stats;
};

export const createPlayer = (name: string, position: Player['position'], age: number, overall: number): Player => {
  const potential = Math.min(99, overall + (age < 24 ? Math.floor(Math.random() * 10) + 5 : Math.floor(Math.random() * 3)));
  
  const possibleDetails = DETAILED_POS_MAP[position];
  const mainPosition = possibleDetails[Math.floor(Math.random() * possibleDetails.length)];
  
  const footRoll = Math.random();
  const preferredFoot: Player['preferredFoot'] = 
    footRoll > 0.30 ? 'RIGHT' : 
    footRoll > 0.05 ? 'LEFT' : 'BOTH';

  return {
    id: Math.random().toString(36).substr(2, 9),
    name,
    position,
    mainPosition,
    secondaryPositions: [],
    preferredFoot,
    age,
    overall,
    energy: 100,
    status: 'fit',
    yellowCards: 0,
    redCards: 0,
    marketValue: Math.round(Math.pow(overall, 3.2) * 12 / 1000) * 1000,
    goals: 0,
    assists: 0,
    potential,
    contractRounds: 99,
    history: [],
    seasonStats: { yellowCards: 0, redCards: 0, matchesSuspended: 0 },
    stats: generateStats(mainPosition, overall, age),
  };
};

// Converte WCTeamData em Team completo
export const buildWCTeam = (data: WCTeamData): Team => {
  const roster = data.players.map(p => createPlayer(p.name, p.position, p.age, p.overall));
  roster.sort((a, b) => b.overall - a.overall);
  const lineup = roster.slice(0, 11).map(p => p.id);
  const avg = (data.attack + data.defense) / 2;

  return {
    id: data.id,
    name: data.name,
    shortName: data.shortName,
    city: '',
    logoColor1: data.logoColor1,
    logoColor2: data.logoColor2,
    // Os assets atuais da Copa embutem texto e badge de grupo na própria imagem.
    // Para manter a UI limpa, usamos o escudo estilizado do app nesses times.
    logoUrl: data.logoUrl,
    attack: data.attack,
    defense: data.defense,
    roster,
    lineup,
    formation: '4-3-3',
    style: 'Equilibrado',
    instructions: { pressing: 'MEDIA', passing: 'MISTO', tempo: 'PADRAO' },
    played: 0, won: 0, drawn: 0, lost: 0, gf: 0, ga: 0, points: 0,
    moral: 80,
    division: 0,
    stadiumCapacity: 60000,
    stadiumName: 'Estádio da Copa',
  };
};

export const CONFEDERATION_LABELS: Record<WCConfederation, string> = {
  UEFA: 'Europa',
  CONMEBOL: 'América do Sul',
  CONCACAF: 'América do Norte e Central',
  AFC: 'Ásia',
  CAF: 'África',
  OFC: 'Oceania',
};

// ========== 48 SELEÇÕES DA COPA DO MUNDO 2026 ==========

export const WC_TEAMS_DATA: WCTeamData[] = [

  // ==================== CONMEBOL (6) ====================
  {
    id: 'wc_brazil', name: 'Brasil', shortName: 'BRA', confederation: 'CONMEBOL',
    logoUrl: '/world_cup_shields/png/brasil.png',
    logoColor1: '#009c3b', logoColor2: '#ffdf00', attack: 93, defense: 90,
    players: [
      { name: 'Alisson', position: 'GOL', age: 33, overall: 88 },
      { name: 'Ederson', position: 'GOL', age: 32, overall: 87 },
      { name: 'Bento', position: 'GOL', age: 25, overall: 80 },
      { name: 'Marquinhos', position: 'ZAG', age: 32, overall: 87 },
      { name: 'Militão', position: 'ZAG', age: 28, overall: 86 },
      { name: 'Gabriel Magalhães', position: 'ZAG', age: 28, overall: 85 },
      { name: 'Beraldo', position: 'ZAG', age: 22, overall: 78 },
      { name: 'Danilo', position: 'LAT', age: 34, overall: 80 },
      { name: 'Vanderson', position: 'LAT', age: 24, overall: 82 },
      { name: 'Arana', position: 'LAT', age: 29, overall: 82 },
      { name: 'Wendell', position: 'LAT', age: 29, overall: 80 },
      { name: 'Casemiro', position: 'VOL', age: 34, overall: 84 },
      { name: 'Bruno Guimarães', position: 'VOL', age: 28, overall: 87 },
      { name: 'André', position: 'VOL', age: 25, overall: 83 },
      { name: 'João Gomes', position: 'VOL', age: 23, overall: 81 },
      { name: 'Lucas Paquetá', position: 'MEI', age: 28, overall: 86 },
      { name: 'Raphinha', position: 'MEI', age: 29, overall: 87 },
      { name: 'Rodrygo', position: 'MEI', age: 25, overall: 88 },
      { name: 'Savinho', position: 'MEI', age: 22, overall: 83 },
      { name: 'Pepê', position: 'MEI', age: 29, overall: 82 },
      { name: 'Vini Jr', position: 'ATA', age: 25, overall: 93 },
      { name: 'Endrick', position: 'ATA', age: 19, overall: 81 },
      { name: 'Estêvão', position: 'ATA', age: 19, overall: 82 },
      { name: 'Igor Jesus', position: 'ATA', age: 27, overall: 80 },
      { name: 'Luiz Henrique', position: 'ATA', age: 25, overall: 82 },
      { name: 'Martinelli', position: 'ATA', age: 25, overall: 84 },
    ]
  },
  {
    id: 'wc_argentina', name: 'Argentina', shortName: 'ARG', confederation: 'CONMEBOL',
    logoUrl: '/world_cup_shields/png/argentina.png',
    logoColor1: '#75AADB', logoColor2: '#FFFFFF', attack: 94, defense: 91,
    players: [
      { name: 'E. Martínez', position: 'GOL', age: 33, overall: 89 },
      { name: 'Rulli', position: 'GOL', age: 34, overall: 82 },
      { name: 'Musso', position: 'GOL', age: 32, overall: 80 },
      { name: 'Romero', position: 'ZAG', age: 28, overall: 86 },
      { name: 'Lisandro Martínez', position: 'ZAG', age: 28, overall: 86 },
      { name: 'Otamendi', position: 'ZAG', age: 38, overall: 80 },
      { name: 'Senesi', position: 'ZAG', age: 29, overall: 82 },
      { name: 'Molina', position: 'LAT', age: 28, overall: 84 },
      { name: 'Montiel', position: 'LAT', age: 29, overall: 82 },
      { name: 'Tagliafico', position: 'LAT', age: 33, overall: 81 },
      { name: 'Acuña', position: 'LAT', age: 34, overall: 80 },
      { name: 'De Paul', position: 'VOL', age: 32, overall: 85 },
      { name: 'Enzo Fernández', position: 'VOL', age: 25, overall: 87 },
      { name: 'Mac Allister', position: 'VOL', age: 27, overall: 86 },
      { name: 'Lo Celso', position: 'VOL', age: 30, overall: 83 },
      { name: 'Messi', position: 'MEI', age: 38, overall: 90 },
      { name: 'Dybala', position: 'MEI', age: 32, overall: 84 },
      { name: 'Garnacho', position: 'MEI', age: 22, overall: 82 },
      { name: 'Nico González', position: 'MEI', age: 28, overall: 83 },
      { name: 'Carboni', position: 'MEI', age: 19, overall: 78 },
      { name: 'Lautaro Martínez', position: 'ATA', age: 28, overall: 89 },
      { name: 'Julián Álvarez', position: 'ATA', age: 26, overall: 88 },
      { name: 'Di María', position: 'ATA', age: 38, overall: 82 },
      { name: 'Castellanos', position: 'ATA', age: 27, overall: 81 },
      { name: 'Simeone', position: 'ATA', age: 26, overall: 79 },
      { name: 'Echeverri', position: 'MEI', age: 19, overall: 76 },
    ]
  },
  {
    id: 'wc_uruguay', name: 'Uruguai', shortName: 'URU', confederation: 'CONMEBOL',
    logoUrl: '/world_cup_shields/png/uruguai.png',
    logoColor1: '#0038a8', logoColor2: '#FFFFFF', attack: 88, defense: 87,
    players: [
      { name: 'Rochet', position: 'GOL', age: 29, overall: 83 },
      { name: 'Sergio Rochet', position: 'GOL', age: 33, overall: 79 },
      { name: 'Israel', position: 'GOL', age: 25, overall: 76 },
      { name: 'Giménez', position: 'ZAG', age: 31, overall: 85 },
      { name: 'Ronald Araújo', position: 'ZAG', age: 27, overall: 87 },
      { name: 'Mathías Olivera', position: 'ZAG', age: 28, overall: 83 },
      { name: 'Bueno', position: 'ZAG', age: 24, overall: 79 },
      { name: 'Nández', position: 'LAT', age: 29, overall: 80 },
      { name: 'Varela', position: 'LAT', age: 25, overall: 79 },
      { name: 'Viña', position: 'LAT', age: 28, overall: 78 },
      { name: 'Saracchi', position: 'LAT', age: 28, overall: 77 },
      { name: 'Valverde', position: 'VOL', age: 27, overall: 89 },
      { name: 'Bentancur', position: 'VOL', age: 29, overall: 83 },
      { name: 'Ugarte', position: 'VOL', age: 25, overall: 84 },
      { name: 'Torreira', position: 'VOL', age: 30, overall: 81 },
      { name: 'De Arrascaeta', position: 'MEI', age: 32, overall: 84 },
      { name: 'Pellistri', position: 'MEI', age: 24, overall: 80 },
      { name: 'Araújo', position: 'MEI', age: 22, overall: 77 },
      { name: 'Torres', position: 'MEI', age: 23, overall: 78 },
      { name: 'Canobbio', position: 'MEI', age: 28, overall: 79 },
      { name: 'Núñez', position: 'ATA', age: 27, overall: 87 },
      { name: 'Suárez', position: 'ATA', age: 39, overall: 78 },
      { name: 'Maxi Araújo', position: 'ATA', age: 24, overall: 80 },
      { name: 'Luciano Rodríguez', position: 'ATA', age: 22, overall: 79 },
      { name: 'Facundo Pellistri', position: 'ATA', age: 24, overall: 78 },
      { name: 'Cristian Olivera', position: 'ATA', age: 24, overall: 77 },
    ]
  },
  {
    id: 'wc_colombia', name: 'Colômbia', shortName: 'COL', confederation: 'CONMEBOL',
    logoUrl: '/world_cup_shields/png/colombia.png',
    logoColor1: '#FCD116', logoColor2: '#003893', attack: 88, defense: 86,
    players: [
      { name: 'Camilo Vargas', position: 'GOL', age: 37, overall: 82 },
      { name: 'Álvaro Montero', position: 'GOL', age: 31, overall: 79 },
      { name: 'Kevin Mier', position: 'GOL', age: 24, overall: 77 },
      { name: 'Davinson Sánchez', position: 'ZAG', age: 30, overall: 82 },
      { name: 'Yerry Mina', position: 'ZAG', age: 31, overall: 81 },
      { name: 'Carlos Cuesta', position: 'ZAG', age: 27, overall: 80 },
      { name: 'Jhon Lucumí', position: 'ZAG', age: 26, overall: 82 },
      { name: 'Daniel Muñoz', position: 'LAT', age: 28, overall: 83 },
      { name: 'Santiago Arias', position: 'LAT', age: 34, overall: 78 },
      { name: 'Johan Mojica', position: 'LAT', age: 32, overall: 80 },
      { name: 'Deiver Machado', position: 'LAT', age: 33, overall: 77 },
      { name: 'Richard Ríos', position: 'VOL', age: 24, overall: 82 },
      { name: 'Jefferson Lerma', position: 'VOL', age: 31, overall: 81 },
      { name: 'Matheus Uribe', position: 'VOL', age: 33, overall: 80 },
      { name: 'Kevin Castaño', position: 'VOL', age: 28, overall: 79 },
      { name: 'James Rodríguez', position: 'MEI', age: 34, overall: 83 },
      { name: 'Jhon Arias', position: 'MEI', age: 27, overall: 83 },
      { name: 'Juan Quintero', position: 'MEI', age: 33, overall: 80 },
      { name: 'Jorge Carrascal', position: 'MEI', age: 28, overall: 79 },
      { name: 'Yáser Asprilla', position: 'MEI', age: 21, overall: 79 },
      { name: 'Luis Díaz', position: 'ATA', age: 29, overall: 87 },
      { name: 'Rafael Borré', position: 'ATA', age: 30, overall: 81 },
      { name: 'Jhon Córdoba', position: 'ATA', age: 32, overall: 80 },
      { name: 'Jhon Durán', position: 'ATA', age: 22, overall: 81 },
      { name: 'Luis Sinisterra', position: 'ATA', age: 27, overall: 80 },
      { name: 'Miguel Borja', position: 'ATA', age: 33, overall: 79 },
    ]
  },
  {
    id: 'wc_ecuador', name: 'Equador', shortName: 'ECU', confederation: 'CONMEBOL',
    logoUrl: '/world_cup_shields/png/equador.png',
    logoColor1: '#FFD100', logoColor2: '#0038A8', attack: 82, defense: 80,
    players: [
      { name: 'Hernán Galíndez', position: 'GOL', age: 39, overall: 78 },
      { name: 'Alexander Domínguez', position: 'GOL', age: 39, overall: 76 },
      { name: 'Moisés Ramírez', position: 'GOL', age: 25, overall: 77 },
      { name: 'Piero Hincapié', position: 'ZAG', age: 24, overall: 83 },
      { name: 'Félix Torres', position: 'ZAG', age: 27, overall: 81 },
      { name: 'William Pacho', position: 'ZAG', age: 23, overall: 82 },
      { name: 'Robert Arboleda', position: 'ZAG', age: 32, overall: 78 },
      { name: 'Angelo Preciado', position: 'LAT', age: 28, overall: 79 },
      { name: 'Pervis Estupiñán', position: 'LAT', age: 28, overall: 82 },
      { name: 'Diego Palacios', position: 'LAT', age: 27, overall: 78 },
      { name: 'Byron Castillo', position: 'LAT', age: 26, overall: 77 },
      { name: 'Moisés Caicedo', position: 'VOL', age: 24, overall: 85 },
      { name: 'Carlos Gruezo', position: 'VOL', age: 31, overall: 78 },
      { name: 'Alan Franco', position: 'VOL', age: 28, overall: 79 },
      { name: 'Jeremy Sarmiento', position: 'VOL', age: 22, overall: 77 },
      { name: 'Gonzalo Plata', position: 'MEI', age: 25, overall: 80 },
      { name: 'Kendry Páez', position: 'MEI', age: 18, overall: 79 },
      { name: 'John Yeboah', position: 'MEI', age: 24, overall: 77 },
      { name: 'Joao Rojas', position: 'MEI', age: 28, overall: 78 },
      { name: 'Ayrton Preciado', position: 'MEI', age: 28, overall: 76 },
      { name: 'Enner Valencia', position: 'ATA', age: 36, overall: 79 },
      { name: 'Michael Estrada', position: 'ATA', age: 30, overall: 78 },
      { name: 'Leonardo Campana', position: 'ATA', age: 26, overall: 77 },
      { name: 'Kevin Rodríguez', position: 'ATA', age: 24, overall: 76 },
      { name: 'Djorkaeff Reasco', position: 'ATA', age: 25, overall: 77 },
      { name: 'Allen Obando', position: 'MEI', age: 22, overall: 75 },
    ]
  },
  {
    id: 'wc_paraguay', name: 'Paraguai', shortName: 'PAR', confederation: 'CONMEBOL',
    logoUrl: '/world_cup_shields/png/paraguai.png',
    logoColor1: '#D52B1E', logoColor2: '#FFFFFF', attack: 78, defense: 77,
    players: [
      { name: 'Antony Silva', position: 'GOL', age: 33, overall: 77 },
      { name: 'Rodrigo Fernández', position: 'GOL', age: 27, overall: 75 },
      { name: 'Carlos Coronel', position: 'GOL', age: 32, overall: 76 },
      { name: 'Gustavo Gómez', position: 'ZAG', age: 33, overall: 81 },
      { name: 'Omar Alderete', position: 'ZAG', age: 29, overall: 79 },
      { name: 'Fabián Balbuena', position: 'ZAG', age: 33, overall: 78 },
      { name: 'Jesús Sagastume', position: 'ZAG', age: 22, overall: 74 },
      { name: 'Robert Rojas', position: 'LAT', age: 29, overall: 78 },
      { name: 'Juan Escobar', position: 'LAT', age: 31, overall: 77 },
      { name: 'Blas Riveros', position: 'LAT', age: 28, overall: 76 },
      { name: 'Matías Rojas', position: 'LAT', age: 31, overall: 76 },
      { name: 'Andrés Cubas', position: 'VOL', age: 29, overall: 79 },
      { name: 'Mathías Villasanti', position: 'VOL', age: 28, overall: 80 },
      { name: 'Diego Gómez', position: 'VOL', age: 22, overall: 77 },
      { name: 'Hernesto Caballero', position: 'VOL', age: 24, overall: 75 },
      { name: 'Miguel Almirón', position: 'MEI', age: 32, overall: 81 },
      { name: 'Julio Enciso', position: 'MEI', age: 21, overall: 79 },
      { name: 'Ramón Sosa', position: 'MEI', age: 25, overall: 78 },
      { name: 'Ángel Romero', position: 'MEI', age: 34, overall: 78 },
      { name: 'Damián Bobadilla', position: 'MEI', age: 28, overall: 77 },
      { name: 'Antonio Sanabria', position: 'ATA', age: 30, overall: 79 },
      { name: 'Isidro Pitta', position: 'ATA', age: 27, overall: 77 },
      { name: 'Adam Bareiro', position: 'ATA', age: 30, overall: 78 },
      { name: 'Alex Arce', position: 'ATA', age: 29, overall: 78 },
      { name: 'Derlis González', position: 'ATA', age: 32, overall: 75 },
      { name: 'Fernando Ovelar', position: 'ATA', age: 20, overall: 73 },
    ]
  },

  // ==================== UEFA (16) ====================
  {
    id: 'wc_france', name: 'França', shortName: 'FRA', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/franca.png',
    logoColor1: '#002395', logoColor2: '#FFFFFF', attack: 94, defense: 91,
    players: [
      { name: 'Maignan', position: 'GOL', age: 31, overall: 88 },
      { name: 'Areola', position: 'GOL', age: 33, overall: 80 },
      { name: 'Samba', position: 'GOL', age: 30, overall: 79 },
      { name: 'Upamecano', position: 'ZAG', age: 27, overall: 85 },
      { name: 'Konaté', position: 'ZAG', age: 27, overall: 86 },
      { name: 'Saliba', position: 'ZAG', age: 25, overall: 87 },
      { name: 'Badiashile', position: 'ZAG', age: 25, overall: 80 },
      { name: 'Theo Hernández', position: 'LAT', age: 28, overall: 87 },
      { name: 'Koundé', position: 'LAT', age: 27, overall: 86 },
      { name: 'Clauss', position: 'LAT', age: 31, overall: 80 },
      { name: 'Mendy', position: 'LAT', age: 31, overall: 82 },
      { name: 'Tchouaméni', position: 'VOL', age: 26, overall: 86 },
      { name: 'Camavinga', position: 'VOL', age: 23, overall: 85 },
      { name: 'Kanté', position: 'VOL', age: 35, overall: 82 },
      { name: 'Rabiot', position: 'VOL', age: 31, overall: 83 },
      { name: 'Griezmann', position: 'MEI', age: 35, overall: 85 },
      { name: 'Dembélé', position: 'MEI', age: 29, overall: 86 },
      { name: 'Olise', position: 'MEI', age: 24, overall: 84 },
      { name: 'Coman', position: 'MEI', age: 30, overall: 83 },
      { name: 'Fofana', position: 'MEI', age: 27, overall: 82 },
      { name: 'Mbappé', position: 'ATA', age: 27, overall: 93 },
      { name: 'Thuram', position: 'ATA', age: 28, overall: 85 },
      { name: 'Giroud', position: 'ATA', age: 39, overall: 79 },
      { name: 'Kolo Muani', position: 'ATA', age: 27, overall: 82 },
      { name: 'Barcola', position: 'ATA', age: 22, overall: 82 },
      { name: 'Lacazette', position: 'ATA', age: 35, overall: 79 },
    ]
  },
  {
    id: 'wc_spain', name: 'Espanha', shortName: 'ESP', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/espanha.png',
    logoColor1: '#AA151B', logoColor2: '#F1BF00', attack: 92, defense: 90,
    players: [
      { name: 'Unai Simón', position: 'GOL', age: 29, overall: 85 },
      { name: 'David Raya', position: 'GOL', age: 30, overall: 86 },
      { name: 'Robert Sánchez', position: 'GOL', age: 29, overall: 80 },
      { name: 'Laporte', position: 'ZAG', age: 32, overall: 84 },
      { name: 'Le Normand', position: 'ZAG', age: 29, overall: 83 },
      { name: 'Vivian', position: 'ZAG', age: 27, overall: 82 },
      { name: 'Pau Cubarsí', position: 'ZAG', age: 19, overall: 82 },
      { name: 'Carvajal', position: 'LAT', age: 34, overall: 85 },
      { name: 'Cucurella', position: 'LAT', age: 28, overall: 83 },
      { name: 'Grimaldo', position: 'LAT', age: 30, overall: 84 },
      { name: 'Jesús Navas', position: 'LAT', age: 40, overall: 78 },
      { name: 'Rodri', position: 'VOL', age: 30, overall: 92 },
      { name: 'Pedri', position: 'VOL', age: 23, overall: 88 },
      { name: 'Gavi', position: 'VOL', age: 21, overall: 84 },
      { name: 'Fabián Ruiz', position: 'VOL', age: 30, overall: 84 },
      { name: 'Dani Olmo', position: 'MEI', age: 28, overall: 86 },
      { name: 'Nico Williams', position: 'MEI', age: 24, overall: 86 },
      { name: 'Fermín López', position: 'MEI', age: 22, overall: 81 },
      { name: 'Oyarzabal', position: 'MEI', age: 29, overall: 83 },
      { name: 'Bryan Gil', position: 'MEI', age: 25, overall: 79 },
      { name: 'Lamine Yamal', position: 'ATA', age: 18, overall: 87 },
      { name: 'Morata', position: 'ATA', age: 33, overall: 83 },
      { name: 'Joselu', position: 'ATA', age: 34, overall: 80 },
      { name: 'Ferran Torres', position: 'ATA', age: 26, overall: 81 },
      { name: 'Ayoze Pérez', position: 'ATA', age: 33, overall: 79 },
      { name: 'Yeremy Pino', position: 'ATA', age: 23, overall: 80 },
    ]
  },
  {
    id: 'wc_england', name: 'Inglaterra', shortName: 'ING', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/inglaterra.png',
    logoColor1: '#FFFFFF', logoColor2: '#CF081F', attack: 93, defense: 89,
    players: [
      { name: 'Pickford', position: 'GOL', age: 32, overall: 84 },
      { name: 'Pope', position: 'GOL', age: 34, overall: 81 },
      { name: 'Henderson', position: 'GOL', age: 29, overall: 79 },
      { name: 'Stones', position: 'ZAG', age: 32, overall: 85 },
      { name: 'Guéhi', position: 'ZAG', age: 26, overall: 83 },
      { name: 'Konsa', position: 'ZAG', age: 28, overall: 82 },
      { name: 'Colwill', position: 'ZAG', age: 23, overall: 81 },
      { name: 'Walker', position: 'LAT', age: 36, overall: 82 },
      { name: 'Alexander-Arnold', position: 'LAT', age: 27, overall: 87 },
      { name: 'Shaw', position: 'LAT', age: 30, overall: 83 },
      { name: 'Trippier', position: 'LAT', age: 35, overall: 81 },
      { name: 'Rice', position: 'VOL', age: 27, overall: 88 },
      { name: 'Bellingham', position: 'VOL', age: 22, overall: 90 },
      { name: 'Mainoo', position: 'VOL', age: 21, overall: 82 },
      { name: 'Gallagher', position: 'VOL', age: 26, overall: 80 },
      { name: 'Foden', position: 'MEI', age: 26, overall: 88 },
      { name: 'Palmer', position: 'MEI', age: 24, overall: 87 },
      { name: 'Gordon', position: 'MEI', age: 25, overall: 82 },
      { name: 'Bowen', position: 'MEI', age: 29, overall: 82 },
      { name: 'Eze', position: 'MEI', age: 28, overall: 83 },
      { name: 'Kane', position: 'ATA', age: 32, overall: 89 },
      { name: 'Saka', position: 'ATA', age: 24, overall: 88 },
      { name: 'Rashford', position: 'ATA', age: 28, overall: 83 },
      { name: 'Watkins', position: 'ATA', age: 30, overall: 83 },
      { name: 'Toney', position: 'ATA', age: 30, overall: 81 },
      { name: 'Nketiah', position: 'ATA', age: 27, overall: 79 },
    ]
  },
  {
    id: 'wc_germany', name: 'Alemanha', shortName: 'ALE', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/alemanha.png',
    logoColor1: '#000000', logoColor2: '#DD0000', attack: 92, defense: 89,
    players: [
      { name: 'Neuer', position: 'GOL', age: 40, overall: 85 },
      { name: 'Ter Stegen', position: 'GOL', age: 34, overall: 86 },
      { name: 'Nübel', position: 'GOL', age: 30, overall: 79 },
      { name: 'Rüdiger', position: 'ZAG', age: 33, overall: 85 },
      { name: 'Tah', position: 'ZAG', age: 30, overall: 84 },
      { name: 'Schlotterbeck', position: 'ZAG', age: 27, overall: 83 },
      { name: 'Koch', position: 'ZAG', age: 29, overall: 80 },
      { name: 'Kimmich', position: 'LAT', age: 31, overall: 88 },
      { name: 'Raum', position: 'LAT', age: 28, overall: 82 },
      { name: 'Henrichs', position: 'LAT', age: 29, overall: 79 },
      { name: 'Mittelstädt', position: 'LAT', age: 28, overall: 80 },
      { name: 'Kroos', position: 'VOL', age: 36, overall: 86 },
      { name: 'Andrich', position: 'VOL', age: 30, overall: 82 },
      { name: 'Can', position: 'VOL', age: 32, overall: 80 },
      { name: 'Groß', position: 'VOL', age: 35, overall: 81 },
      { name: 'Musiala', position: 'MEI', age: 23, overall: 88 },
      { name: 'Wirtz', position: 'MEI', age: 23, overall: 88 },
      { name: 'Sané', position: 'MEI', age: 30, overall: 84 },
      { name: 'Brandt', position: 'MEI', age: 30, overall: 82 },
      { name: 'Müller', position: 'MEI', age: 36, overall: 80 },
      { name: 'Havertz', position: 'ATA', age: 27, overall: 84 },
      { name: 'Füllkrug', position: 'ATA', age: 33, overall: 82 },
      { name: 'Undav', position: 'ATA', age: 30, overall: 81 },
      { name: 'Beier', position: 'ATA', age: 23, overall: 80 },
      { name: 'Nmecha', position: 'ATA', age: 27, overall: 79 },
      { name: 'Adeyemi', position: 'ATA', age: 24, overall: 80 },
    ]
  },
  {
    id: 'wc_portugal', name: 'Portugal', shortName: 'POR', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/portugal.png',
    logoColor1: '#006600', logoColor2: '#FF0000', attack: 91, defense: 88,
    players: [
      { name: 'Diogo Costa', position: 'GOL', age: 26, overall: 85 },
      { name: 'Rui Patrício', position: 'GOL', age: 38, overall: 78 },
      { name: 'José Sá', position: 'GOL', age: 33, overall: 80 },
      { name: 'Rúben Dias', position: 'ZAG', age: 29, overall: 87 },
      { name: 'Pepe', position: 'ZAG', age: 43, overall: 78 },
      { name: 'António Silva', position: 'ZAG', age: 22, overall: 82 },
      { name: 'Gonçalo Inácio', position: 'ZAG', age: 25, overall: 83 },
      { name: 'Cancelo', position: 'LAT', age: 32, overall: 85 },
      { name: 'Nuno Mendes', position: 'LAT', age: 24, overall: 84 },
      { name: 'Dalot', position: 'LAT', age: 27, overall: 83 },
      { name: 'Nelson Semedo', position: 'LAT', age: 32, overall: 80 },
      { name: 'Vitinha', position: 'VOL', age: 26, overall: 86 },
      { name: 'Bruno Fernandes', position: 'VOL', age: 31, overall: 87 },
      { name: 'Palhinha', position: 'VOL', age: 31, overall: 84 },
      { name: 'Renato Sanches', position: 'VOL', age: 28, overall: 79 },
      { name: 'Bernardo Silva', position: 'MEI', age: 31, overall: 88 },
      { name: 'Rafael Leão', position: 'MEI', age: 27, overall: 86 },
      { name: 'João Félix', position: 'MEI', age: 26, overall: 82 },
      { name: 'Otávio', position: 'MEI', age: 31, overall: 81 },
      { name: 'Pedro Neto', position: 'MEI', age: 26, overall: 83 },
      { name: 'Cristiano Ronaldo', position: 'ATA', age: 41, overall: 84 },
      { name: 'Gonçalo Ramos', position: 'ATA', age: 25, overall: 83 },
      { name: 'Diogo Jota', position: 'ATA', age: 29, overall: 84 },
      { name: 'João Pedro', position: 'ATA', age: 25, overall: 80 },
      { name: 'Francisco Trincão', position: 'ATA', age: 26, overall: 79 },
      { name: 'Gyökeres', position: 'ATA', age: 28, overall: 86 },
    ]
  },
  {
    id: 'wc_netherlands', name: 'Holanda', shortName: 'HOL', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/holanda.png',
    logoColor1: '#FF6600', logoColor2: '#FFFFFF', attack: 89, defense: 87,
    players: [
      { name: 'Verbruggen', position: 'GOL', age: 24, overall: 83 },
      { name: 'Flekken', position: 'GOL', age: 33, overall: 80 },
      { name: 'Bijlow', position: 'GOL', age: 28, overall: 79 },
      { name: 'Van Dijk', position: 'ZAG', age: 34, overall: 87 },
      { name: 'De Vrij', position: 'ZAG', age: 34, overall: 82 },
      { name: 'Aké', position: 'ZAG', age: 31, overall: 84 },
      { name: 'De Ligt', position: 'ZAG', age: 26, overall: 83 },
      { name: 'Dumfries', position: 'LAT', age: 30, overall: 82 },
      { name: 'Blind', position: 'LAT', age: 36, overall: 79 },
      { name: 'Geertruida', position: 'LAT', age: 25, overall: 81 },
      { name: 'Dest', position: 'LAT', age: 25, overall: 78 },
      { name: 'Frenkie de Jong', position: 'VOL', age: 29, overall: 86 },
      { name: 'Schouten', position: 'VOL', age: 28, overall: 82 },
      { name: 'Gravenberch', position: 'VOL', age: 24, overall: 83 },
      { name: 'Timber', position: 'VOL', age: 25, overall: 83 },
      { name: 'Simons', position: 'MEI', age: 23, overall: 85 },
      { name: 'Reijnders', position: 'MEI', age: 28, overall: 84 },
      { name: 'Berghuis', position: 'MEI', age: 34, overall: 80 },
      { name: 'Veerman', position: 'MEI', age: 27, overall: 81 },
      { name: 'Malen', position: 'MEI', age: 27, overall: 82 },
      { name: 'Gakpo', position: 'ATA', age: 27, overall: 85 },
      { name: 'Depay', position: 'ATA', age: 32, overall: 82 },
      { name: 'Weghorst', position: 'ATA', age: 33, overall: 79 },
      { name: 'Zirkzee', position: 'ATA', age: 25, overall: 81 },
      { name: 'Brobbey', position: 'ATA', age: 24, overall: 80 },
      { name: 'Kluivert', position: 'ATA', age: 25, overall: 78 },
    ]
  },
  {
    id: 'wc_belgium', name: 'Bélgica', shortName: 'BEL', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/belgica.png',
    logoColor1: '#000000', logoColor2: '#FD0', attack: 88, defense: 85,
    players: [
      { name: 'Courtois', position: 'GOL', age: 34, overall: 88 },
      { name: 'Casteels', position: 'GOL', age: 34, overall: 82 },
      { name: 'Kaminski', position: 'GOL', age: 32, overall: 77 },
      { name: 'Vertonghen', position: 'ZAG', age: 39, overall: 78 },
      { name: 'Faes', position: 'ZAG', age: 26, overall: 81 },
      { name: 'Theate', position: 'ZAG', age: 26, overall: 80 },
      { name: 'Debast', position: 'ZAG', age: 22, overall: 79 },
      { name: 'Castagne', position: 'LAT', age: 30, overall: 81 },
      { name: 'Meunier', position: 'LAT', age: 34, overall: 79 },
      { name: 'Carrasco', position: 'LAT', age: 32, overall: 80 },
      { name: 'De Cuyper', position: 'LAT', age: 24, overall: 79 },
      { name: 'De Bruyne', position: 'VOL', age: 35, overall: 88 },
      { name: 'Tielemans', position: 'VOL', age: 29, overall: 83 },
      { name: 'Onana', position: 'VOL', age: 25, overall: 82 },
      { name: 'Mangala', position: 'VOL', age: 26, overall: 80 },
      { name: 'Doku', position: 'MEI', age: 24, overall: 83 },
      { name: 'Trossard', position: 'MEI', age: 31, overall: 83 },
      { name: 'Bakayoko', position: 'MEI', age: 23, overall: 81 },
      { name: 'Vanaken', position: 'MEI', age: 33, overall: 80 },
      { name: 'De Ketelaere', position: 'MEI', age: 25, overall: 80 },
      { name: 'Lukaku', position: 'ATA', age: 33, overall: 85 },
      { name: 'Openda', position: 'ATA', age: 26, overall: 83 },
      { name: 'Batshuayi', position: 'ATA', age: 32, overall: 78 },
      { name: 'Leandro Trossard', position: 'ATA', age: 31, overall: 82 },
      { name: 'Dries Mertens', position: 'ATA', age: 39, overall: 77 },
      { name: 'Lukébakio', position: 'ATA', age: 27, overall: 79 },
    ]
  },
  {
    id: 'wc_croatia', name: 'Croácia', shortName: 'CRO', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/croacia.png',
    logoColor1: '#FF0000', logoColor2: '#FFFFFF', attack: 87, defense: 85,
    players: [
      { name: 'Livaković', position: 'GOL', age: 31, overall: 83 },
      { name: 'Ivušić', position: 'GOL', age: 31, overall: 78 },
      { name: 'Labrović', position: 'GOL', age: 26, overall: 76 },
      { name: 'Gvardiol', position: 'ZAG', age: 24, overall: 86 },
      { name: 'Šutalo', position: 'ZAG', age: 24, overall: 81 },
      { name: 'Erlić', position: 'ZAG', age: 28, overall: 80 },
      { name: 'Pongračić', position: 'ZAG', age: 28, overall: 79 },
      { name: 'Juranović', position: 'LAT', age: 31, overall: 80 },
      { name: 'Sosa', position: 'LAT', age: 27, overall: 81 },
      { name: 'Stanišić', position: 'LAT', age: 25, overall: 80 },
      { name: 'Perišić', position: 'LAT', age: 37, overall: 79 },
      { name: 'Modrić', position: 'VOL', age: 40, overall: 85 },
      { name: 'Kovačić', position: 'VOL', age: 32, overall: 84 },
      { name: 'Brozović', position: 'VOL', age: 33, overall: 83 },
      { name: 'Sučić', position: 'VOL', age: 22, overall: 80 },
      { name: 'Pašalić', position: 'MEI', age: 31, overall: 81 },
      { name: 'Majer', position: 'MEI', age: 28, overall: 82 },
      { name: 'Vlašić', position: 'MEI', age: 28, overall: 80 },
      { name: 'Ivanušec', position: 'MEI', age: 28, overall: 79 },
      { name: 'Baturina', position: 'MEI', age: 21, overall: 78 },
      { name: 'Kramarić', position: 'ATA', age: 34, overall: 82 },
      { name: 'Petković', position: 'ATA', age: 30, overall: 79 },
      { name: 'Budimir', position: 'ATA', age: 34, overall: 80 },
      { name: 'Livaja', position: 'ATA', age: 31, overall: 78 },
      { name: 'Oršić', position: 'ATA', age: 32, overall: 78 },
      { name: 'Matanović', position: 'ATA', age: 22, overall: 76 },
    ]
  },
  {
    id: 'wc_switzerland', name: 'Suíça', shortName: 'SUI', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/suica.png',
    logoColor1: '#FF0000', logoColor2: '#FFFFFF', attack: 83, defense: 83,
    players: [
      { name: 'Sommer', position: 'GOL', age: 37, overall: 84 },
      { name: 'Kobel', position: 'GOL', age: 28, overall: 83 },
      { name: 'Mvogo', position: 'GOL', age: 32, overall: 77 },
      { name: 'Akanji', position: 'ZAG', age: 30, overall: 85 },
      { name: 'Ricardo Rodríguez', position: 'ZAG', age: 33, overall: 80 },
      { name: 'Schär', position: 'ZAG', age: 34, overall: 81 },
      { name: 'Elvedi', position: 'ZAG', age: 29, overall: 82 },
      { name: 'Widmer', position: 'LAT', age: 33, overall: 79 },
      { name: 'Stergiou', position: 'LAT', age: 22, overall: 77 },
      { name: 'Zuber', position: 'LAT', age: 33, overall: 78 },
      { name: 'Fernandes', position: 'LAT', age: 26, overall: 78 },
      { name: 'Xhaka', position: 'VOL', age: 33, overall: 85 },
      { name: 'Freuler', position: 'VOL', age: 33, overall: 82 },
      { name: 'Zakaria', position: 'VOL', age: 29, overall: 81 },
      { name: 'Aebischer', position: 'VOL', age: 27, overall: 80 },
      { name: 'Shaqiri', position: 'MEI', age: 34, overall: 79 },
      { name: 'Ndoye', position: 'MEI', age: 24, overall: 80 },
      { name: 'Rieder', position: 'MEI', age: 23, overall: 78 },
      { name: 'Steffen', position: 'MEI', age: 28, overall: 78 },
      { name: 'Okafor', position: 'MEI', age: 26, overall: 79 },
      { name: 'Embolo', position: 'ATA', age: 29, overall: 80 },
      { name: 'Duah', position: 'ATA', age: 28, overall: 77 },
      { name: 'Amdouni', position: 'ATA', age: 24, overall: 78 },
      { name: 'Seferović', position: 'ATA', age: 34, overall: 76 },
      { name: 'Zeqiri', position: 'ATA', age: 27, overall: 76 },
      { name: 'Jashari', position: 'VOL', age: 23, overall: 78 },
    ]
  },
  {
    id: 'wc_austria', name: 'Áustria', shortName: 'AUT', confederation: 'UEFA',
    logoColor1: '#ED2939', logoColor2: '#FFFFFF', attack: 83, defense: 82,
    players: [
      { name: 'Pentz', position: 'GOL', age: 29, overall: 79 },
      { name: 'Lindner', position: 'GOL', age: 30, overall: 77 },
      { name: 'Hedl', position: 'GOL', age: 23, overall: 75 },
      { name: 'Alaba', position: 'ZAG', age: 33, overall: 85 },
      { name: 'Danso', position: 'ZAG', age: 27, overall: 81 },
      { name: 'Wöber', position: 'ZAG', age: 28, overall: 79 },
      { name: 'Lienhart', position: 'ZAG', age: 29, overall: 78 },
      { name: 'Posch', position: 'LAT', age: 27, overall: 80 },
      { name: 'Mwene', position: 'LAT', age: 30, overall: 78 },
      { name: 'Prass', position: 'LAT', age: 24, overall: 78 },
      { name: 'Querfeld', position: 'LAT', age: 22, overall: 76 },
      { name: 'Laimer', position: 'VOL', age: 29, overall: 83 },
      { name: 'Seiwald', position: 'VOL', age: 24, overall: 81 },
      { name: 'Grillitsch', position: 'VOL', age: 30, overall: 80 },
      { name: 'Wimmer', position: 'VOL', age: 23, overall: 78 },
      { name: 'Sabitzer', position: 'MEI', age: 32, overall: 83 },
      { name: 'Baumgartner', position: 'MEI', age: 27, overall: 81 },
      { name: 'Schmid', position: 'MEI', age: 24, overall: 79 },
      { name: 'Grüll', position: 'MEI', age: 28, overall: 78 },
      { name: 'Romano', position: 'MEI', age: 26, overall: 77 },
      { name: 'Arnautović', position: 'ATA', age: 37, overall: 79 },
      { name: 'Gregoritsch', position: 'ATA', age: 32, overall: 79 },
      { name: 'Adamu', position: 'ATA', age: 24, overall: 76 },
      { name: 'Seidl', position: 'ATA', age: 24, overall: 75 },
      { name: 'Entrup', position: 'ATA', age: 28, overall: 76 },
      { name: 'Kainz', position: 'MEI', age: 33, overall: 77 },
    ]
  },
  {
    id: 'wc_scotland', name: 'Escócia', shortName: 'ESC', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/escocia.png',
    logoColor1: '#003399', logoColor2: '#FFFFFF', attack: 79, defense: 78,
    players: [
      { name: 'Gunn', position: 'GOL', age: 30, overall: 78 },
      { name: 'Gordon', position: 'GOL', age: 33, overall: 77 },
      { name: 'Clark', position: 'GOL', age: 31, overall: 75 },
      { name: 'Tierney', position: 'ZAG', age: 29, overall: 80 },
      { name: 'Hendry', position: 'ZAG', age: 31, overall: 78 },
      { name: 'McKenna', position: 'ZAG', age: 29, overall: 78 },
      { name: 'Porteous', position: 'ZAG', age: 27, overall: 77 },
      { name: 'Robertson', position: 'LAT', age: 32, overall: 83 },
      { name: 'Ralston', position: 'LAT', age: 27, overall: 76 },
      { name: 'Hickey', position: 'LAT', age: 24, overall: 77 },
      { name: 'Patterson', position: 'LAT', age: 25, overall: 76 },
      { name: 'McTominay', position: 'VOL', age: 29, overall: 82 },
      { name: 'McGinn', position: 'VOL', age: 31, overall: 80 },
      { name: 'Gilmour', position: 'VOL', age: 25, overall: 79 },
      { name: 'McGregor', position: 'VOL', age: 33, overall: 78 },
      { name: 'Christie', position: 'MEI', age: 31, overall: 77 },
      { name: 'Forrest', position: 'MEI', age: 33, overall: 77 },
      { name: 'Fraser', position: 'MEI', age: 32, overall: 76 },
      { name: 'Morgan', position: 'MEI', age: 24, overall: 76 },
      { name: 'McLean', position: 'MEI', age: 31, overall: 77 },
      { name: 'Adams', position: 'ATA', age: 29, overall: 79 },
      { name: 'Dykes', position: 'ATA', age: 31, overall: 77 },
      { name: 'Shankland', position: 'ATA', age: 31, overall: 76 },
      { name: 'McGinn', position: 'ATA', age: 25, overall: 75 },
      { name: 'Nisbet', position: 'ATA', age: 29, overall: 76 },
      { name: 'Conway', position: 'ATA', age: 28, overall: 75 },
    ]
  },

  // ==================== CONCACAF (6) ====================
  {
    id: 'wc_usa', name: 'Estados Unidos', shortName: 'EUA', confederation: 'CONCACAF',
    logoColor1: '#002868', logoColor2: '#BF0A30', attack: 84, defense: 82,
    players: [
      { name: 'Turner', position: 'GOL', age: 32, overall: 81 },
      { name: 'Horvath', position: 'GOL', age: 29, overall: 77 },
      { name: 'Johnson', position: 'GOL', age: 26, overall: 76 },
      { name: 'McKenzie', position: 'ZAG', age: 27, overall: 79 },
      { name: 'Richards', position: 'ZAG', age: 26, overall: 79 },
      { name: 'Robinson', position: 'ZAG', age: 27, overall: 78 },
      { name: 'Ream', position: 'ZAG', age: 39, overall: 77 },
      { name: 'Dest', position: 'LAT', age: 25, overall: 80 },
      { name: 'Robinson', position: 'LAT', age: 27, overall: 79 },
      { name: 'Scally', position: 'LAT', age: 23, overall: 78 },
      { name: 'Yedlin', position: 'LAT', age: 33, overall: 76 },
      { name: 'McKennie', position: 'VOL', age: 27, overall: 82 },
      { name: 'Adams', position: 'VOL', age: 27, overall: 81 },
      { name: 'Musah', position: 'VOL', age: 23, overall: 81 },
      { name: 'Acosta', position: 'VOL', age: 28, overall: 79 },
      { name: 'Reyna', position: 'MEI', age: 23, overall: 82 },
      { name: 'Aaronson', position: 'MEI', age: 25, overall: 79 },
      { name: 'De la Torre', position: 'MEI', age: 28, overall: 77 },
      { name: 'Tillman', position: 'MEI', age: 24, overall: 78 },
      { name: 'Cardoso', position: 'MEI', age: 23, overall: 76 },
      { name: 'Pulisic', position: 'ATA', age: 27, overall: 85 },
      { name: 'Weah', position: 'ATA', age: 26, overall: 81 },
      { name: 'Balogun', position: 'ATA', age: 25, overall: 80 },
      { name: 'Pepi', position: 'ATA', age: 23, overall: 79 },
      { name: 'Wright', position: 'ATA', age: 26, overall: 78 },
      { name: 'Sargent', position: 'ATA', age: 26, overall: 78 },
    ]
  },
  {
    id: 'wc_mexico', name: 'México', shortName: 'MEX', confederation: 'CONCACAF',
    logoUrl: '/world_cup_shields/png/mexico.png',
    logoColor1: '#006847', logoColor2: '#CE1126', attack: 83, defense: 81,
    players: [
      { name: 'Ochoa', position: 'GOL', age: 40, overall: 79 },
      { name: 'Malagón', position: 'GOL', age: 28, overall: 79 },
      { name: 'Acevedo', position: 'GOL', age: 28, overall: 77 },
      { name: 'Montes', position: 'ZAG', age: 29, overall: 80 },
      { name: 'Vázquez', position: 'ZAG', age: 28, overall: 79 },
      { name: 'Araujo', position: 'ZAG', age: 32, overall: 78 },
      { name: 'Reyes', position: 'ZAG', age: 24, overall: 77 },
      { name: 'J. Sánchez', position: 'LAT', age: 28, overall: 80 },
      { name: 'Arteaga', position: 'LAT', age: 28, overall: 79 },
      { name: 'Gallardo', position: 'LAT', age: 30, overall: 78 },
      { name: 'K. Álvarez', position: 'LAT', age: 26, overall: 79 },
      { name: 'Edson Álvarez', position: 'VOL', age: 28, overall: 83 },
      { name: 'Romo', position: 'VOL', age: 29, overall: 80 },
      { name: 'Gutiérrez', position: 'VOL', age: 29, overall: 78 },
      { name: 'Pineda', position: 'VOL', age: 26, overall: 78 },
      { name: 'Lozano', position: 'MEI', age: 30, overall: 81 },
      { name: 'Vega', position: 'MEI', age: 28, overall: 80 },
      { name: 'Chávez', position: 'MEI', age: 27, overall: 78 },
      { name: 'Lainez', position: 'MEI', age: 25, overall: 77 },
      { name: 'Antuna', position: 'MEI', age: 28, overall: 77 },
      { name: 'Santi Giménez', position: 'ATA', age: 25, overall: 82 },
      { name: 'Raúl Jiménez', position: 'ATA', age: 35, overall: 79 },
      { name: 'Henry Martín', position: 'ATA', age: 33, overall: 78 },
      { name: 'Huerta', position: 'ATA', age: 28, overall: 78 },
      { name: 'Quiñones', position: 'ATA', age: 29, overall: 77 },
      { name: 'Berterame', position: 'ATA', age: 28, overall: 77 },
    ]
  },
  {
    id: 'wc_canada', name: 'Canadá', shortName: 'CAN', confederation: 'CONCACAF',
    logoUrl: '/world_cup_shields/png/canada.png',
    logoColor1: '#FF0000', logoColor2: '#FFFFFF', attack: 80, defense: 78,
    players: [
      { name: 'Crepeau', position: 'GOL', age: 32, overall: 78 },
      { name: 'Borjan', position: 'GOL', age: 39, overall: 76 },
      { name: 'St. Clair', position: 'GOL', age: 27, overall: 76 },
      { name: 'Johnston', position: 'ZAG', age: 26, overall: 78 },
      { name: 'Miller', position: 'ZAG', age: 27, overall: 77 },
      { name: 'Bombito', position: 'ZAG', age: 25, overall: 77 },
      { name: 'Waterman', position: 'ZAG', age: 30, overall: 76 },
      { name: 'Adekugbe', position: 'LAT', age: 31, overall: 76 },
      { name: 'Laryea', position: 'LAT', age: 31, overall: 76 },
      { name: 'Davies', position: 'LAT', age: 25, overall: 84 },
      { name: 'De Fougerolles', position: 'LAT', age: 24, overall: 74 },
      { name: 'Eustáquio', position: 'VOL', age: 28, overall: 79 },
      { name: 'Koné', position: 'VOL', age: 25, overall: 78 },
      { name: 'Piette', position: 'VOL', age: 32, overall: 76 },
      { name: 'Osorio', position: 'VOL', age: 26, overall: 77 },
      { name: 'Buchanan', position: 'MEI', age: 27, overall: 79 },
      { name: 'Millar', position: 'MEI', age: 27, overall: 77 },
      { name: 'Shaffelburg', position: 'MEI', age: 25, overall: 76 },
      { name: 'Oluwaseyi', position: 'MEI', age: 26, overall: 76 },
      { name: 'Choinière', position: 'MEI', age: 28, overall: 75 },
      { name: 'Jonathan David', position: 'ATA', age: 26, overall: 83 },
      { name: 'Larin', position: 'ATA', age: 31, overall: 78 },
      { name: 'Bair', position: 'ATA', age: 24, overall: 76 },
      { name: 'Corbeanu', position: 'ATA', age: 24, overall: 76 },
      { name: 'Ugbo', position: 'ATA', age: 27, overall: 77 },
      { name: 'Russell-Rowe', position: 'ATA', age: 22, overall: 74 },
    ]
  },

  // ==================== AFC (9) ====================
  {
    id: 'wc_japan', name: 'Japão', shortName: 'JAP', confederation: 'AFC',
    logoUrl: '/world_cup_shields/png/japao.png',
    logoColor1: '#000080', logoColor2: '#FFFFFF', attack: 85, defense: 83,
    players: [
      { name: 'Suzuki', position: 'GOL', age: 28, overall: 81 },
      { name: 'Kawashima', position: 'GOL', age: 43, overall: 74 },
      { name: 'Gu Sung-yun', position: 'GOL', age: 32, overall: 77 },
      { name: 'Tomiyasu', position: 'ZAG', age: 27, overall: 82 },
      { name: 'Itakura', position: 'ZAG', age: 29, overall: 80 },
      { name: 'Taniguchi', position: 'ZAG', age: 33, overall: 78 },
      { name: 'Machida', position: 'ZAG', age: 28, overall: 79 },
      { name: 'Sugawara', position: 'LAT', age: 25, overall: 79 },
      { name: 'Nagatomo', position: 'LAT', age: 39, overall: 74 },
      { name: 'Ito (H.)', position: 'LAT', age: 31, overall: 79 },
      { name: 'Nakayama', position: 'LAT', age: 29, overall: 77 },
      { name: 'Endo', position: 'VOL', age: 33, overall: 82 },
      { name: 'Tanaka', position: 'VOL', age: 28, overall: 80 },
      { name: 'Morita', position: 'VOL', age: 28, overall: 79 },
      { name: 'Doan', position: 'VOL', age: 28, overall: 79 },
      { name: 'Kubo', position: 'MEI', age: 25, overall: 83 },
      { name: 'Kamada', position: 'MEI', age: 30, overall: 81 },
      { name: 'Mitoma', position: 'MEI', age: 29, overall: 82 },
      { name: 'Minamino', position: 'MEI', age: 31, overall: 79 },
      { name: 'Ito (J.)', position: 'MEI', age: 25, overall: 80 },
      { name: 'Osako', position: 'ATA', age: 36, overall: 77 },
      { name: 'Ueda', position: 'ATA', age: 28, overall: 79 },
      { name: 'Maeda', position: 'ATA', age: 29, overall: 78 },
      { name: 'Furuhashi', position: 'ATA', age: 31, overall: 78 },
      { name: 'Asano', position: 'ATA', age: 31, overall: 78 },
      { name: 'Suzuki (Y.)', position: 'ATA', age: 24, overall: 77 },
    ]
  },
  {
    id: 'wc_southkorea', name: 'Coreia do Sul', shortName: 'COR', confederation: 'AFC',
    logoUrl: '/world_cup_shields/png/coreia_do_sul.png',
    logoColor1: '#CD2E3A', logoColor2: '#0047A0', attack: 84, defense: 82,
    players: [
      { name: 'Kim Seung-gyu', position: 'GOL', age: 36, overall: 79 },
      { name: 'Jo Hyeon-woo', position: 'GOL', age: 35, overall: 78 },
      { name: 'Song Bum-keun', position: 'GOL', age: 28, overall: 78 },
      { name: 'Kim Min-jae', position: 'ZAG', age: 29, overall: 86 },
      { name: 'Kim Young-gwon', position: 'ZAG', age: 36, overall: 78 },
      { name: 'Cho Yu-min', position: 'ZAG', age: 26, overall: 78 },
      { name: 'Park Ji-su', position: 'ZAG', age: 28, overall: 77 },
      { name: 'Kim Jin-su', position: 'LAT', age: 34, overall: 77 },
      { name: 'Kim Moon-hwan', position: 'LAT', age: 31, overall: 77 },
      { name: 'Hong Chul', position: 'LAT', age: 36, overall: 76 },
      { name: 'Lee Ki-je', position: 'LAT', age: 35, overall: 76 },
      { name: 'Hwang In-beom', position: 'VOL', age: 30, overall: 80 },
      { name: 'Jung Woo-young', position: 'VOL', age: 36, overall: 78 },
      { name: 'Paik Seung-ho', position: 'VOL', age: 29, overall: 79 },
      { name: 'Lee Jae-sung', position: 'VOL', age: 34, overall: 79 },
      { name: 'Lee Kang-in', position: 'MEI', age: 25, overall: 84 },
      { name: 'Kwon Chang-hoon', position: 'MEI', age: 32, overall: 78 },
      { name: 'Na Sang-ho', position: 'MEI', age: 30, overall: 77 },
      { name: 'Jeong Sang-bin', position: 'MEI', age: 24, overall: 78 },
      { name: 'Yang Hyun-jun', position: 'MEI', age: 23, overall: 77 },
      { name: 'Son Heung-min', position: 'ATA', age: 33, overall: 86 },
      { name: 'Hwang Hee-chan', position: 'ATA', age: 30, overall: 81 },
      { name: 'Cho Gue-sung', position: 'ATA', age: 28, overall: 79 },
      { name: 'Oh Hyeon-gyu', position: 'ATA', age: 24, overall: 78 },
      { name: 'Song Min-kyu', position: 'ATA', age: 27, overall: 77 },
      { name: 'Hwang Ui-jo', position: 'ATA', age: 32, overall: 78 },
    ]
  },
  {
    id: 'wc_australia', name: 'Austrália', shortName: 'AUS2', confederation: 'AFC',
    logoUrl: '/world_cup_shields/png/australia.png',
    logoColor1: '#00843D', logoColor2: '#FFCD00', attack: 79, defense: 77,
    players: [
      { name: 'Ryan', position: 'GOL', age: 34, overall: 78 },
      { name: 'Vukovic', position: 'GOL', age: 41, overall: 74 },
      { name: 'Gauci', position: 'GOL', age: 24, overall: 74 },
      { name: 'Souttar', position: 'ZAG', age: 28, overall: 78 },
      { name: 'Rowles', position: 'ZAG', age: 27, overall: 76 },
      { name: 'Burgess', position: 'ZAG', age: 27, overall: 76 },
      { name: 'Wright', position: 'ZAG', age: 28, overall: 75 },
      { name: 'Karacic', position: 'LAT', age: 31, overall: 75 },
      { name: 'Behich', position: 'LAT', age: 30, overall: 76 },
      { name: 'Deng', position: 'LAT', age: 28, overall: 75 },
      { name: 'Atkinson', position: 'LAT', age: 27, overall: 74 },
      { name: 'Mooy', position: 'VOL', age: 35, overall: 77 },
      { name: 'Irvine', position: 'VOL', age: 33, overall: 77 },
      { name: 'McGree', position: 'VOL', age: 26, overall: 77 },
      { name: 'Baccus', position: 'VOL', age: 28, overall: 75 },
      { name: 'Hrustic', position: 'MEI', age: 28, overall: 77 },
      { name: 'Mabil', position: 'MEI', age: 28, overall: 76 },
      { name: 'Boyle', position: 'MEI', age: 33, overall: 76 },
      { name: 'Goodwin', position: 'MEI', age: 25, overall: 76 },
      { name: 'Devlin', position: 'MEI', age: 26, overall: 75 },
      { name: 'Duke', position: 'ATA', age: 32, overall: 77 },
      { name: 'Maclaren', position: 'ATA', age: 33, overall: 77 },
      { name: 'Kuol', position: 'ATA', age: 21, overall: 75 },
      { name: 'Taggart', position: 'ATA', age: 32, overall: 76 },
      { name: 'Cummings', position: 'ATA', age: 28, overall: 74 },
      { name: 'Sotirio', position: 'ATA', age: 32, overall: 73 },
    ]
  },
  {
    id: 'wc_saudiarabia', name: 'Arábia Saudita', shortName: 'ARS', confederation: 'AFC',
    logoUrl: '/world_cup_shields/png/arabia_saudita.png',
    logoColor1: '#006C35', logoColor2: '#FFFFFF', attack: 78, defense: 76,
    players: [
      { name: 'Al-Owais', position: 'GOL', age: 34, overall: 78 },
      { name: 'Al-Yami', position: 'GOL', age: 29, overall: 76 },
      { name: 'Al-Aqidi', position: 'GOL', age: 25, overall: 74 },
      { name: 'Al-Amri', position: 'ZAG', age: 29, overall: 77 },
      { name: 'Al-Bulaihi', position: 'ZAG', age: 37, overall: 76 },
      { name: 'Tambakti', position: 'ZAG', age: 27, overall: 77 },
      { name: 'Al-Ghannam', position: 'ZAG', age: 29, overall: 76 },
      { name: 'Abdulhamid', position: 'LAT', age: 27, overall: 77 },
      { name: 'Al-Shahrani', position: 'LAT', age: 33, overall: 76 },
      { name: 'Al-Burayk', position: 'LAT', age: 31, overall: 76 },
      { name: 'Bahebri', position: 'LAT', age: 33, overall: 74 },
      { name: 'Kanno', position: 'VOL', age: 36, overall: 78 },
      { name: 'Al-Malki', position: 'VOL', age: 32, overall: 76 },
      { name: 'Al-Khaibari', position: 'VOL', age: 26, overall: 75 },
      { name: 'Otayf', position: 'VOL', age: 29, overall: 76 },
      { name: 'Al-Dawsari', position: 'MEI', age: 33, overall: 80 },
      { name: 'Al-Shehri', position: 'MEI', age: 32, overall: 78 },
      { name: 'Asiri', position: 'MEI', age: 27, overall: 76 },
      { name: 'Al-Qahtani', position: 'MEI', age: 24, overall: 75 },
      { name: 'Al-Zubaidi', position: 'MEI', age: 26, overall: 74 },
      { name: 'Al-Buraikan', position: 'ATA', age: 26, overall: 78 },
      { name: 'Al-Hamdan', position: 'ATA', age: 29, overall: 76 },
      { name: 'Al-Obaid', position: 'ATA', age: 25, overall: 74 },
      { name: 'Maran', position: 'ATA', age: 28, overall: 75 },
      { name: 'Al-Hassan', position: 'ATA', age: 23, overall: 73 },
      { name: 'Al-Najei', position: 'ATA', age: 24, overall: 74 },
    ]
  },
  {
    id: 'wc_iran', name: 'Irã', shortName: 'IRN', confederation: 'AFC',
    logoUrl: '/world_cup_shields/png/ira.png',
    logoColor1: '#239F40', logoColor2: '#DA0000', attack: 79, defense: 78,
    players: [
      { name: 'Beiranvand', position: 'GOL', age: 34, overall: 79 },
      { name: 'Abedzadeh', position: 'GOL', age: 28, overall: 76 },
      { name: 'Niazmand', position: 'GOL', age: 29, overall: 75 },
      { name: 'Hosseini', position: 'ZAG', age: 28, overall: 78 },
      { name: 'Pouraliganji', position: 'ZAG', age: 34, overall: 77 },
      { name: 'Kanaani', position: 'ZAG', age: 30, overall: 76 },
      { name: 'Khalilzadeh', position: 'ZAG', age: 34, overall: 76 },
      { name: 'Moharrami', position: 'LAT', age: 29, overall: 78 },
      { name: 'Hajsafi', position: 'LAT', age: 40, overall: 75 },
      { name: 'Rezaeian', position: 'LAT', age: 34, overall: 76 },
      { name: 'Karimi', position: 'LAT', age: 28, overall: 75 },
      { name: 'Ezatolahi', position: 'VOL', age: 30, overall: 78 },
      { name: 'Nourollahi', position: 'VOL', age: 33, overall: 77 },
      { name: 'Ghoddos', position: 'VOL', age: 32, overall: 77 },
      { name: 'Torabi', position: 'VOL', age: 31, overall: 76 },
      { name: 'Jahanbakhsh', position: 'MEI', age: 33, overall: 78 },
      { name: 'Amiri', position: 'MEI', age: 27, overall: 77 },
      { name: 'Gholizadeh', position: 'MEI', age: 30, overall: 77 },
      { name: 'Qasemi', position: 'MEI', age: 26, overall: 75 },
      { name: 'Askari', position: 'MEI', age: 25, overall: 74 },
      { name: 'Taremi', position: 'ATA', age: 34, overall: 82 },
      { name: 'Azmoun', position: 'ATA', age: 31, overall: 81 },
      { name: 'Ansarifard', position: 'ATA', age: 36, overall: 76 },
      { name: 'Mohebi', position: 'ATA', age: 25, overall: 75 },
      { name: 'Ghayedi', position: 'ATA', age: 24, overall: 75 },
      { name: 'Zahedi', position: 'ATA', age: 28, overall: 76 },
    ]
  },
  {
    id: 'wc_qatar', name: 'Catar', shortName: 'QAT', confederation: 'AFC',
    logoUrl: '/world_cup_shields/png/catar.png',
    logoColor1: '#8A1538', logoColor2: '#FFFFFF', attack: 76, defense: 75,
    players: [
      { name: 'Barsham', position: 'GOL', age: 28, overall: 77 },
      { name: 'Al Sheeb', position: 'GOL', age: 33, overall: 75 },
      { name: 'Yousuf Hassan', position: 'GOL', age: 25, overall: 73 },
      { name: 'Pedro Miguel', position: 'ZAG', age: 36, overall: 76 },
      { name: 'Khoukhi', position: 'ZAG', age: 35, overall: 75 },
      { name: 'Ahmed', position: 'ZAG', age: 27, overall: 75 },
      { name: 'Salman', position: 'ZAG', age: 28, overall: 74 },
      { name: 'Hassan', position: 'LAT', age: 29, overall: 75 },
      { name: 'Al-Rawi', position: 'LAT', age: 28, overall: 74 },
      { name: 'Ro-Ro', position: 'LAT', age: 30, overall: 75 },
      { name: 'Bakri', position: 'LAT', age: 26, overall: 73 },
      { name: 'Boudiaf', position: 'VOL', age: 39, overall: 75 },
      { name: 'Al-Haydos', position: 'VOL', age: 35, overall: 76 },
      { name: 'Hatem', position: 'VOL', age: 28, overall: 74 },
      { name: 'Waad', position: 'VOL', age: 27, overall: 73 },
      { name: 'Afif', position: 'MEI', age: 29, overall: 79 },
      { name: 'Al-Haydos', position: 'MEI', age: 35, overall: 76 },
      { name: 'Madibo', position: 'MEI', age: 28, overall: 75 },
      { name: 'Muntari', position: 'MEI', age: 28, overall: 74 },
      { name: 'Ahmed Alaa', position: 'MEI', age: 24, overall: 73 },
      { name: 'Ali', position: 'ATA', age: 28, overall: 77 },
      { name: 'Mohammed', position: 'ATA', age: 30, overall: 76 },
      { name: 'Al-Rawi', position: 'ATA', age: 27, overall: 74 },
      { name: 'Ismail', position: 'ATA', age: 25, overall: 73 },
      { name: 'Correia', position: 'ATA', age: 29, overall: 74 },
      { name: 'Meshaal', position: 'ATA', age: 23, overall: 72 },
    ]
  },
  {
    id: 'wc_iraq', name: 'Iraque', shortName: 'IRQ', confederation: 'AFC',
    logoUrl: '/world_cup_shields/png/iraque.png',
    logoColor1: '#007A3D', logoColor2: '#FFFFFF', attack: 76, defense: 74,
    players: [
      { name: 'Jalal Hassan', position: 'GOL', age: 32, overall: 76 },
      { name: 'Fahad Talib', position: 'GOL', age: 28, overall: 74 },
      { name: 'Noor Sabri', position: 'GOL', age: 24, overall: 73 },
      { name: 'Ali Adnan', position: 'ZAG', age: 33, overall: 77 },
      { name: 'Rebin Sulaka', position: 'ZAG', age: 28, overall: 76 },
      { name: 'Ibrahim Bayesh', position: 'ZAG', age: 30, overall: 75 },
      { name: 'Safaa Hadi', position: 'ZAG', age: 31, overall: 74 },
      { name: 'Ahmed Yasin', position: 'LAT', age: 30, overall: 75 },
      { name: 'Sherko Kareem', position: 'LAT', age: 27, overall: 74 },
      { name: 'Ali Faez', position: 'LAT', age: 26, overall: 73 },
      { name: 'Mohammed Qasim', position: 'LAT', age: 25, overall: 73 },
      { name: 'Amjad Attwan', position: 'VOL', age: 30, overall: 76 },
      { name: 'Saad Natiq', position: 'VOL', age: 29, overall: 75 },
      { name: 'Hussein Ali', position: 'VOL', age: 27, overall: 74 },
      { name: 'Alaa Abbas', position: 'VOL', age: 26, overall: 74 },
      { name: 'Mohanad Ali', position: 'MEI', age: 25, overall: 77 },
      { name: 'Ayman Hussein', position: 'MEI', age: 29, overall: 76 },
      { name: 'Ibrahim Bayesh', position: 'MEI', age: 30, overall: 75 },
      { name: 'Ali Jasim', position: 'MEI', age: 22, overall: 74 },
      { name: 'Zidane Iqbal', position: 'MEI', age: 23, overall: 75 },
      { name: 'Aymen Hussein', position: 'ATA', age: 31, overall: 77 },
      { name: 'Ali Al-Hamadi', position: 'ATA', age: 23, overall: 76 },
      { name: 'Ahmed Yasin', position: 'ATA', age: 30, overall: 75 },
      { name: 'Karrar Jasim', position: 'ATA', age: 26, overall: 73 },
      { name: 'Mohammed Dawood', position: 'ATA', age: 27, overall: 74 },
      { name: 'Alaa Mhawi', position: 'ATA', age: 28, overall: 73 },
    ]
  },
  {
    id: 'wc_uzbekistan', name: 'Uzbequistão', shortName: 'UZB', confederation: 'AFC',
    logoUrl: '/world_cup_shields/png/uzbequistao.png',
    logoColor1: '#0099B5', logoColor2: '#1EB53A', attack: 77, defense: 75,
    players: [
      { name: 'Nematov', position: 'GOL', age: 27, overall: 76 },
      { name: 'Ergashev', position: 'GOL', age: 30, overall: 75 },
      { name: 'Turapov', position: 'GOL', age: 24, overall: 73 },
      { name: 'Khasanov', position: 'ZAG', age: 27, overall: 76 },
      { name: 'Sayfiev', position: 'ZAG', age: 29, overall: 75 },
      { name: 'Ismailov', position: 'ZAG', age: 28, overall: 75 },
      { name: 'Khashimov', position: 'ZAG', age: 25, overall: 74 },
      { name: 'Yakhshiboev', position: 'LAT', age: 31, overall: 75 },
      { name: 'Kobilov', position: 'LAT', age: 26, overall: 74 },
      { name: 'Alijonov', position: 'LAT', age: 24, overall: 73 },
      { name: 'Ganiev', position: 'LAT', age: 28, overall: 74 },
      { name: 'Fayzullaev', position: 'VOL', age: 22, overall: 78 },
      { name: 'Tukhtasinov', position: 'VOL', age: 28, overall: 75 },
      { name: 'Urunov', position: 'VOL', age: 27, overall: 75 },
      { name: 'Abdullaev', position: 'VOL', age: 26, overall: 74 },
      { name: 'Shomurodov', position: 'MEI', age: 29, overall: 78 },
      { name: 'Jaloliddinov', position: 'MEI', age: 24, overall: 76 },
      { name: 'Kendjaev', position: 'MEI', age: 28, overall: 75 },
      { name: 'Rashidov', position: 'MEI', age: 28, overall: 74 },
      { name: 'Nasimov', position: 'MEI', age: 25, overall: 73 },
      { name: 'Sergeev', position: 'ATA', age: 25, overall: 76 },
      { name: 'Odilov', position: 'ATA', age: 27, overall: 75 },
      { name: 'Bikmaev', position: 'ATA', age: 28, overall: 74 },
      { name: 'Tursunov', position: 'ATA', age: 24, overall: 73 },
      { name: 'Khamdamov', position: 'ATA', age: 23, overall: 73 },
      { name: 'Mirzaev', position: 'ATA', age: 26, overall: 74 },
    ]
  },

  // ==================== CAF (9) ====================
  {
    id: 'wc_morocco', name: 'Marrocos', shortName: 'MAR', confederation: 'CAF',
    logoUrl: '/world_cup_shields/png/marrocos.png',
    logoColor1: '#C1272D', logoColor2: '#006233', attack: 86, defense: 85,
    players: [
      { name: 'Bounou', position: 'GOL', age: 35, overall: 85 },
      { name: 'Munir', position: 'GOL', age: 28, overall: 79 },
      { name: 'Tagnaouti', position: 'GOL', age: 30, overall: 76 },
      { name: 'Hakimi', position: 'ZAG', age: 27, overall: 87 },
      { name: 'Saïss', position: 'ZAG', age: 36, overall: 80 },
      { name: 'Aguerd', position: 'ZAG', age: 30, overall: 82 },
      { name: 'El Yamiq', position: 'ZAG', age: 32, overall: 79 },
      { name: 'Mazraoui', position: 'LAT', age: 28, overall: 83 },
      { name: 'Attiat-Allah', position: 'LAT', age: 30, overall: 78 },
      { name: 'Dari', position: 'LAT', age: 27, overall: 79 },
      { name: 'Hakimi (A.)', position: 'LAT', age: 26, overall: 77 },
      { name: 'Amrabat', position: 'VOL', age: 29, overall: 82 },
      { name: 'Ounahi', position: 'VOL', age: 26, overall: 80 },
      { name: 'Amallah', position: 'VOL', age: 30, overall: 79 },
      { name: 'El Khannouss', position: 'VOL', age: 20, overall: 79 },
      { name: 'Ziyech', position: 'MEI', age: 33, overall: 83 },
      { name: 'Boufal', position: 'MEI', age: 33, overall: 79 },
      { name: 'Diaz', position: 'MEI', age: 28, overall: 80 },
      { name: 'Akhomach', position: 'MEI', age: 22, overall: 77 },
      { name: 'Adli', position: 'MEI', age: 26, overall: 78 },
      { name: 'En-Nesyri', position: 'ATA', age: 29, overall: 82 },
      { name: 'Hamdallah', position: 'ATA', age: 36, overall: 78 },
      { name: 'Rahimi', position: 'ATA', age: 28, overall: 79 },
      { name: 'El Kaabi', position: 'ATA', age: 33, overall: 78 },
      { name: 'Aboukhlal', position: 'ATA', age: 26, overall: 77 },
      { name: 'Brahim Díaz', position: 'ATA', age: 26, overall: 81 },
    ]
  },
  {
    id: 'wc_senegal', name: 'Senegal', shortName: 'SEN', confederation: 'CAF',
    logoUrl: '/world_cup_shields/png/senegal.png',
    logoColor1: '#009639', logoColor2: '#FDEF42', attack: 84, defense: 82,
    players: [
      { name: 'É. Mendy', position: 'GOL', age: 34, overall: 83 },
      { name: 'A. Diallo', position: 'GOL', age: 30, overall: 77 },
      { name: 'S. Dieng', position: 'GOL', age: 32, overall: 78 },
      { name: 'Koulibaly', position: 'ZAG', age: 35, overall: 82 },
      { name: 'A. Diallo', position: 'ZAG', age: 28, overall: 80 },
      { name: 'Diakité', position: 'ZAG', age: 28, overall: 79 },
      { name: 'Niakhaté', position: 'ZAG', age: 30, overall: 79 },
      { name: 'Sabaly', position: 'LAT', age: 32, overall: 78 },
      { name: 'Jakobs', position: 'LAT', age: 28, overall: 77 },
      { name: 'Ballo-Touré', position: 'LAT', age: 29, overall: 76 },
      { name: 'Formose', position: 'LAT', age: 26, overall: 76 },
      { name: 'Gueye', position: 'VOL', age: 37, overall: 80 },
      { name: 'N. Mendy', position: 'VOL', age: 28, overall: 79 },
      { name: 'P. Gueye', position: 'VOL', age: 27, overall: 79 },
      { name: 'Kouyaté', position: 'VOL', age: 36, overall: 77 },
      { name: 'Sarr', position: 'MEI', age: 28, overall: 80 },
      { name: 'Diatta', position: 'MEI', age: 26, overall: 79 },
      { name: 'Iliman Ndiaye', position: 'MEI', age: 26, overall: 80 },
      { name: 'P. Sarr', position: 'MEI', age: 22, overall: 78 },
      { name: 'Mama Baldé', position: 'MEI', age: 28, overall: 77 },
      { name: 'Jackson', position: 'ATA', age: 25, overall: 82 },
      { name: 'Dia', position: 'ATA', age: 29, overall: 80 },
      { name: 'Diedhiou', position: 'ATA', age: 33, overall: 77 },
      { name: 'Habib Diallo', position: 'ATA', age: 30, overall: 78 },
      { name: 'Dieng', position: 'ATA', age: 26, overall: 78 },
      { name: 'Mané', position: 'ATA', age: 34, overall: 82 },
    ]
  },
  {
    id: 'wc_egypt', name: 'Egito', shortName: 'EGI', confederation: 'CAF',
    logoUrl: '/world_cup_shields/png/egito.png',
    logoColor1: '#CE1126', logoColor2: '#FFFFFF', attack: 82, defense: 79,
    players: [
      { name: 'El Shenawy', position: 'GOL', age: 37, overall: 79 },
      { name: 'Abou Gabal', position: 'GOL', age: 38, overall: 77 },
      { name: 'Hamza', position: 'GOL', age: 24, overall: 74 },
      { name: 'Hegazy', position: 'ZAG', age: 35, overall: 78 },
      { name: 'Abdelmonem', position: 'ZAG', age: 27, overall: 78 },
      { name: 'Fatouh', position: 'ZAG', age: 26, overall: 76 },
      { name: 'Fathi', position: 'ZAG', age: 32, overall: 77 },
      { name: 'Ashour', position: 'LAT', age: 26, overall: 76 },
      { name: 'Kamal', position: 'LAT', age: 28, overall: 76 },
      { name: 'Hamdy', position: 'LAT', age: 30, overall: 75 },
      { name: 'Eid', position: 'LAT', age: 25, overall: 74 },
      { name: 'El Neny', position: 'VOL', age: 33, overall: 78 },
      { name: 'Fathy', position: 'VOL', age: 27, overall: 77 },
      { name: 'Kouka', position: 'VOL', age: 29, overall: 76 },
      { name: 'Elneny', position: 'VOL', age: 33, overall: 77 },
      { name: 'Trezeguet', position: 'MEI', age: 31, overall: 78 },
      { name: 'Emam Ashour', position: 'MEI', age: 28, overall: 78 },
      { name: 'Ibrahim Adel', position: 'MEI', age: 24, overall: 77 },
      { name: 'Afsha', position: 'MEI', age: 29, overall: 77 },
      { name: 'Zizo', position: 'MEI', age: 30, overall: 77 },
      { name: 'Salah', position: 'ATA', age: 33, overall: 88 },
      { name: 'Marmoush', position: 'ATA', age: 27, overall: 83 },
      { name: 'Mostafa Mohamed', position: 'ATA', age: 28, overall: 79 },
      { name: 'Hassan', position: 'ATA', age: 26, overall: 76 },
      { name: 'Sobhi', position: 'ATA', age: 29, overall: 76 },
      { name: 'Maher', position: 'ATA', age: 24, overall: 74 },
    ]
  },
  {
    id: 'wc_southafrica', name: 'África do Sul', shortName: 'AFS', confederation: 'CAF',
    logoUrl: '/world_cup_shields/png/africa_do_sul.png',
    logoColor1: '#007A4D', logoColor2: '#FFB612', attack: 76, defense: 74,
    players: [
      { name: 'R. Williams', position: 'GOL', age: 32, overall: 76 },
      { name: 'Mothwa', position: 'GOL', age: 30, overall: 75 },
      { name: 'Bvuma', position: 'GOL', age: 30, overall: 74 },
      { name: 'Mphahlele', position: 'ZAG', age: 34, overall: 75 },
      { name: 'Mudau', position: 'ZAG', age: 28, overall: 75 },
      { name: 'Kekana', position: 'ZAG', age: 25, overall: 74 },
      { name: 'Dortley', position: 'ZAG', age: 22, overall: 74 },
      { name: 'Modiba', position: 'LAT', age: 30, overall: 75 },
      { name: 'De Reuck', position: 'LAT', age: 28, overall: 75 },
      { name: 'Mashego', position: 'LAT', age: 24, overall: 74 },
      { name: 'Sithole', position: 'LAT', age: 26, overall: 73 },
      { name: 'Mokoena', position: 'VOL', age: 27, overall: 77 },
      { name: 'Aubaas', position: 'VOL', age: 24, overall: 75 },
      { name: 'Mkhulise', position: 'VOL', age: 27, overall: 74 },
      { name: 'Mokwena', position: 'VOL', age: 26, overall: 73 },
      { name: 'Zwane', position: 'MEI', age: 26, overall: 76 },
      { name: 'Tau', position: 'MEI', age: 30, overall: 77 },
      { name: 'Mokotjo', position: 'MEI', age: 35, overall: 74 },
      { name: 'Foster', position: 'MEI', age: 24, overall: 75 },
      { name: 'Mabiliso', position: 'MEI', age: 27, overall: 74 },
      { name: 'Shalulile', position: 'ATA', age: 32, overall: 77 },
      { name: 'Appollis', position: 'ATA', age: 24, overall: 76 },
      { name: 'Lepasa', position: 'ATA', age: 28, overall: 75 },
      { name: 'Makgopa', position: 'ATA', age: 26, overall: 75 },
      { name: 'Pule', position: 'ATA', age: 32, overall: 74 },
      { name: 'Mothiba', position: 'ATA', age: 30, overall: 74 },
    ]
  },
  {
    id: 'wc_tunisia', name: 'Tunísia', shortName: 'TUN', confederation: 'CAF',
    logoUrl: '/world_cup_shields/png/tunisia.png',
    logoColor1: '#E70013', logoColor2: '#FFFFFF', attack: 78, defense: 77,
    players: [
      { name: 'Dahmen', position: 'GOL', age: 28, overall: 77 },
      { name: 'Hassen', position: 'GOL', age: 31, overall: 76 },
      { name: 'Ben Said', position: 'GOL', age: 25, overall: 73 },
      { name: 'Bronn', position: 'ZAG', age: 31, overall: 77 },
      { name: 'Talbi', position: 'ZAG', age: 28, overall: 78 },
      { name: 'Meriah', position: 'ZAG', age: 33, overall: 76 },
      { name: 'Ghaylen Chaalali', position: 'ZAG', age: 28, overall: 75 },
      { name: 'Drager', position: 'LAT', age: 30, overall: 76 },
      { name: 'Abdi', position: 'LAT', age: 28, overall: 76 },
      { name: 'Maaloul', position: 'LAT', age: 36, overall: 75 },
      { name: 'Kechrida', position: 'LAT', age: 28, overall: 75 },
      { name: 'Skhiri', position: 'VOL', age: 30, overall: 80 },
      { name: 'Laidouni', position: 'VOL', age: 32, overall: 78 },
      { name: 'Mejbri', position: 'VOL', age: 23, overall: 77 },
      { name: 'Sassi', position: 'VOL', age: 34, overall: 76 },
      { name: 'Msakni', position: 'MEI', age: 36, overall: 77 },
      { name: 'Slimane', position: 'MEI', age: 24, overall: 76 },
      { name: 'Ben Slimane', position: 'MEI', age: 25, overall: 76 },
      { name: 'Aïdouni', position: 'MEI', age: 26, overall: 75 },
      { name: 'Rafia', position: 'MEI', age: 27, overall: 75 },
      { name: 'Khazri', position: 'ATA', age: 35, overall: 77 },
      { name: 'Jaziri', position: 'ATA', age: 30, overall: 76 },
      { name: 'Khenissi', position: 'ATA', age: 33, overall: 75 },
      { name: 'Sliti', position: 'ATA', age: 34, overall: 75 },
      { name: 'Altaher', position: 'ATA', age: 24, overall: 73 },
      { name: 'Sghaier', position: 'ATA', age: 22, overall: 73 },
    ]
  },
  {
    id: 'wc_drcongo', name: 'RD Congo', shortName: 'RDC', confederation: 'CAF',
    logoUrl: '/world_cup_shields/png/rd_congo.png',
    logoColor1: '#007FFF', logoColor2: '#CE1126', attack: 77, defense: 75,
    players: [
      { name: 'Bertaud', position: 'GOL', age: 29, overall: 76 },
      { name: 'Kiassumbua', position: 'GOL', age: 27, overall: 74 },
      { name: 'Mpasi', position: 'GOL', age: 24, overall: 72 },
      { name: 'Mbemba', position: 'ZAG', age: 32, overall: 79 },
      { name: 'Luyindama', position: 'ZAG', age: 32, overall: 76 },
      { name: 'Inonga', position: 'ZAG', age: 27, overall: 75 },
      { name: 'Lusamba', position: 'ZAG', age: 28, overall: 74 },
      { name: 'Masuaku', position: 'LAT', age: 32, overall: 76 },
      { name: 'Kayembe', position: 'LAT', age: 28, overall: 75 },
      { name: 'Ngonda', position: 'LAT', age: 26, overall: 74 },
      { name: 'Molebatsi', position: 'LAT', age: 25, overall: 73 },
      { name: 'Wissa', position: 'VOL', age: 28, overall: 79 },
      { name: 'Imbula', position: 'VOL', age: 33, overall: 76 },
      { name: 'Mbokani', position: 'VOL', age: 39, overall: 74 },
      { name: 'Kayembe (N.)', position: 'VOL', age: 27, overall: 76 },
      { name: 'Bakambu', position: 'MEI', age: 33, overall: 78 },
      { name: 'Kakuta', position: 'MEI', age: 33, overall: 76 },
      { name: 'Bongonda', position: 'MEI', age: 28, overall: 77 },
      { name: 'Mbemba (Y.)', position: 'MEI', age: 23, overall: 74 },
      { name: 'Moutoussamy', position: 'MEI', age: 28, overall: 75 },
      { name: 'Batshuayi', position: 'ATA', age: 32, overall: 77 },
      { name: 'Malango', position: 'ATA', age: 26, overall: 75 },
      { name: 'Wissa (Y.)', position: 'ATA', age: 28, overall: 78 },
      { name: 'Ngoma', position: 'ATA', age: 25, overall: 73 },
      { name: 'Mayi', position: 'ATA', age: 24, overall: 73 },
      { name: 'Lilepo', position: 'ATA', age: 27, overall: 74 },
    ]
  },

  // ==================== OFC (1) ====================
  {
    id: 'wc_newzealand', name: 'Nova Zelândia', shortName: 'NZL', confederation: 'OFC',
    logoUrl: '/world_cup_shields/png/nova_zelandia.png',
    logoColor1: '#000000', logoColor2: '#FFFFFF', attack: 70, defense: 69,
    players: [
      { name: 'Sail', position: 'GOL', age: 27, overall: 74 },
      { name: 'Marinovic', position: 'GOL', age: 35, overall: 73 },
      { name: 'Paulsen', position: 'GOL', age: 24, overall: 71 },
      { name: 'Payne', position: 'ZAG', age: 30, overall: 74 },
      { name: 'Tuiloma', position: 'ZAG', age: 31, overall: 73 },
      { name: 'Boxall', position: 'ZAG', age: 34, overall: 73 },
      { name: 'Surman', position: 'ZAG', age: 25, overall: 72 },
      { name: 'Cacace', position: 'LAT', age: 25, overall: 74 },
      { name: 'Thomas', position: 'LAT', age: 28, overall: 73 },
      { name: 'Stensness', position: 'LAT', age: 25, overall: 73 },
      { name: 'Lewis', position: 'LAT', age: 27, overall: 72 },
      { name: 'Singh', position: 'VOL', age: 27, overall: 75 },
      { name: 'Bell', position: 'VOL', age: 29, overall: 74 },
      { name: 'Stamenic', position: 'VOL', age: 25, overall: 74 },
      { name: 'Just', position: 'VOL', age: 28, overall: 73 },
      { name: 'Garbett', position: 'MEI', age: 23, overall: 74 },
      { name: 'Waine', position: 'MEI', age: 25, overall: 73 },
      { name: 'Barbarouses', position: 'MEI', age: 35, overall: 73 },
      { name: 'McCowatt', position: 'MEI', age: 26, overall: 72 },
      { name: 'Rojas', position: 'MEI', age: 25, overall: 72 },
      { name: 'Wood', position: 'ATA', age: 34, overall: 75 },
      { name: 'Woud', position: 'ATA', age: 27, overall: 73 },
      { name: 'Greenslade', position: 'ATA', age: 22, overall: 72 },
      { name: 'Sheridan', position: 'ATA', age: 24, overall: 71 },
      { name: 'Elliot', position: 'ATA', age: 26, overall: 72 },
      { name: 'Mattocks', position: 'ATA', age: 24, overall: 71 },
    ]
  },
  {
    id: 'wc_czech', name: 'República Tcheca', shortName: 'CZE', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/republica_tcheca.png',
    logoColor1: '#D7141A', logoColor2: '#11457E', attack: 78, defense: 80,
    players: [
      { name: 'Stanek', position: 'GOL', age: 30, overall: 80 },
      { name: 'Kovar', position: 'GOL', age: 26, overall: 78 },
      { name: 'Holes', position: 'ZAG', age: 33, overall: 79 },
      { name: 'Hranac', position: 'ZAG', age: 26, overall: 78 },
      { name: 'Coufal', position: 'LAT', age: 33, overall: 80 },
      { name: 'Soucek', position: 'VOL', age: 31, overall: 83 },
      { name: 'Provod', position: 'MEI', age: 29, overall: 79 },
      { name: 'Schick', position: 'ATA', age: 30, overall: 82 },
      { name: 'Hlozek', position: 'ATA', age: 23, overall: 79 },
      { name: 'Chory', position: 'ATA', age: 31, overall: 77 },
      { name: 'Lingr', position: 'MEI', age: 27, overall: 76 },
    ]
  },
  {
    id: 'wc_bosnia', name: 'Bósnia', shortName: 'BIH', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/bosnia.png',
    logoColor1: '#002395', logoColor2: '#FECB00', attack: 76, defense: 75,
    players: [
      { name: 'Vasilj', position: 'GOL', age: 30, overall: 77 },
      { name: 'Hadzikadunic', position: 'ZAG', age: 27, overall: 76 },
      { name: 'Ahmedhodzic', position: 'ZAG', age: 27, overall: 79 },
      { name: 'Kolasinac', position: 'LAT', age: 32, overall: 80 },
      { name: 'Dedid', position: 'LAT', age: 23, overall: 80 },
      { name: 'Krunic', position: 'VOL', age: 32, overall: 78 },
      { name: 'Tahirovic', position: 'VOL', age: 23, overall: 76 },
      { name: 'Dzeko', position: 'ATA', age: 40, overall: 81 },
      { name: 'Demirovic', position: 'ATA', age: 28, overall: 81 },
      { name: 'Tabakovic', position: 'ATA', age: 31, overall: 76 },
      { name: 'Gigovic', position: 'MEI', age: 24, overall: 74 },
    ]
  },
  {
    id: 'wc_haiti', name: 'Haiti', shortName: 'HAI', confederation: 'CONCACAF',
    logoUrl: '/world_cup_shields/png/haiti.png',
    logoColor1: '#00209F', logoColor2: '#D21034', attack: 70, defense: 68,
    players: [
      { name: 'Placide', position: 'GOL', age: 38, overall: 74 },
      { name: 'Adé', position: 'ZAG', age: 31, overall: 72 },
      { name: 'Arcus', position: 'LAT', age: 30, overall: 73 },
      { name: 'Pierre', position: 'VOL', age: 33, overall: 71 },
      { name: 'Nazon', position: 'ATA', age: 32, overall: 75 },
      { name: 'Pierrot', position: 'ATA', age: 31, overall: 74 },
      { name: 'Etienne', position: 'MEI', age: 29, overall: 72 },
      { name: 'Picault', position: 'ATA', age: 35, overall: 73 },
      { name: 'Metusala', position: 'ZAG', age: 26, overall: 70 },
      { name: 'Saba', position: 'VOL', age: 31, overall: 71 },
      { name: 'Lienard', position: 'GOL', age: 25, overall: 68 },
    ]
  },
  {
    id: 'wc_turkey', name: 'Turquia', shortName: 'TUR', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/turquia.png',
    logoColor1: '#E30A17', logoColor2: '#FFFFFF', attack: 82, defense: 79,
    players: [
      { name: 'Günok', position: 'GOL', age: 37, overall: 81 },
      { name: 'Bardakcı', position: 'ZAG', age: 31, overall: 80 },
      { name: 'Demiral', position: 'ZAG', age: 28, overall: 81 },
      { name: 'Kadıoğlu', position: 'LAT', age: 26, overall: 82 },
      { name: 'Çalhanoğlu', position: 'VOL', age: 32, overall: 86 },
      { name: 'Kökçü', position: 'MEI', age: 25, overall: 81 },
      { name: 'Güler', position: 'MEI', age: 21, overall: 82 },
      { name: 'Yılmaz', position: 'ATA', age: 26, overall: 79 },
      { name: 'Yıldız', position: 'ATA', age: 21, overall: 80 },
      { name: 'Tosun', position: 'ATA', age: 35, overall: 77 },
      { name: 'Akaydin', position: 'ZAG', age: 32, overall: 76 },
    ]
  },
  {
    id: 'wc_curacao', name: 'Curaçao', shortName: 'CUW', confederation: 'CONCACAF',
    logoUrl: '/world_cup_shields/png/curacao.png',
    logoColor1: '#002B7F', logoColor2: '#F9E814', attack: 71, defense: 69,
    players: [
      { name: 'Room', position: 'GOL', age: 37, overall: 75 },
      { name: 'Martina', position: 'ZAG', age: 36, overall: 73 },
      { name: 'Van Eijma', position: 'ZAG', age: 32, overall: 71 },
      { name: 'Bacuna (L)', position: 'VOL', age: 34, overall: 74 },
      { name: 'Bacuna (J)', position: 'MEI', age: 28, overall: 73 },
      { name: 'Janga', position: 'ATA', age: 34, overall: 72 },
      { name: 'Zivkovic', position: 'ATA', age: 29, overall: 74 },
      { name: 'Margaritha', position: 'ATA', age: 26, overall: 71 },
      { name: 'Roemeratoe', position: 'VOL', age: 27, overall: 72 },
      { name: 'Anita', position: 'VOL', age: 37, overall: 73 },
      { name: 'Bodak', position: 'GOL', age: 23, overall: 68 },
    ]
  },
  {
    id: 'wc_ivorycoast', name: 'Costa do Marfim', shortName: 'CIV', confederation: 'CAF',
    logoUrl: '/world_cup_shields/png/costa_do_marfim.png',
    logoColor1: '#FF8200', logoColor2: '#009E60', attack: 82, defense: 81,
    players: [
      { name: 'Fofana (Y)', position: 'GOL', age: 26, overall: 79 },
      { name: 'Ndicka', position: 'ZAG', age: 26, overall: 82 },
      { name: 'Kossounou', position: 'ZAG', age: 25, overall: 81 },
      { name: 'Singo', position: 'LAT', age: 25, overall: 80 },
      { name: 'Kessié', position: 'VOL', age: 29, overall: 83 },
      { name: 'Fofana (S)', position: 'VOL', age: 31, overall: 82 },
      { name: 'Adinga', position: 'MEI', age: 24, overall: 80 },
      { name: 'Haller', position: 'ATA', age: 32, overall: 82 },
      { name: 'Diakité', position: 'ATA', age: 22, overall: 79 },
      { name: 'Pépé', position: 'ATA', age: 31, overall: 78 },
      { name: 'Konaté', position: 'ATA', age: 22, overall: 77 },
    ]
  },
  {
    id: 'wc_sweden', name: 'Suécia', shortName: 'SUE', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/suecia.png',
    logoColor1: '#FECC00', logoColor2: '#006AA7', attack: 83, defense: 80,
    players: [
      { name: 'Olsen', position: 'GOL', age: 36, overall: 80 },
      { name: 'Lindelöf', position: 'ZAG', age: 31, overall: 81 },
      { name: 'Hien', position: 'ZAG', age: 27, overall: 80 },
      { name: 'Augustinsson', position: 'LAT', age: 32, overall: 78 },
      { name: 'Cajuste', position: 'VOL', age: 26, overall: 79 },
      { name: 'Larsson', position: 'VOL', age: 22, overall: 78 },
      { name: 'Kulusevski', position: 'MEI', age: 26, overall: 84 },
      { name: 'Gyökeres', position: 'ATA', age: 28, overall: 85 },
      { name: 'Isak', position: 'ATA', age: 26, overall: 84 },
      { name: 'Elanga', position: 'ATA', age: 24, overall: 79 },
      { name: 'Forsberg', position: 'MEI', age: 34, overall: 80 },
    ]
  },
  {
    id: 'wc_capeverde', name: 'Cabo Verde', shortName: 'CPV', confederation: 'CAF',
    logoUrl: '/world_cup_shields/png/cabo_verde.png',
    logoColor1: '#003893', logoColor2: '#FFFFFF', attack: 74, defense: 73,
    players: [
      { name: 'Vozinha', position: 'GOL', age: 40, overall: 75 },
      { name: 'Costa', position: 'ZAG', age: 31, overall: 74 },
      { name: 'Pico', position: 'ZAG', age: 33, overall: 74 },
      { name: 'Moreira', position: 'LAT', age: 30, overall: 75 },
      { name: 'Pina', position: 'VOL', age: 27, overall: 73 },
      { name: 'Monteiro', position: 'MEI', age: 32, overall: 76 },
      { name: 'Mendes', position: 'ATA', age: 35, overall: 77 },
      { name: 'Bebé', position: 'ATA', age: 35, overall: 74 },
      { name: 'Cabral', position: 'ATA', age: 27, overall: 75 },
      { name: 'Rodrigues', position: 'ATA', age: 31, overall: 76 },
      { name: 'Duarte', position: 'MEI', age: 27, overall: 73 },
    ]
  },
  {
    id: 'wc_norway', name: 'Noruega', shortName: 'NOR', confederation: 'UEFA',
    logoUrl: '/world_cup_shields/png/noruega.png',
    logoColor1: '#EF2B2D', logoColor2: '#00205B', attack: 85, defense: 78,
    players: [
      { name: 'Nyland', position: 'GOL', age: 35, overall: 80 },
      { name: 'Ostigard', position: 'ZAG', age: 26, overall: 79 },
      { name: 'Ajer', position: 'ZAG', age: 28, overall: 78 },
      { name: 'Ryerson', position: 'LAT', age: 28, overall: 81 },
      { name: 'Berge', position: 'VOL', age: 28, overall: 81 },
      { name: 'Odegaard', position: 'MEI', age: 27, overall: 89 },
      { name: 'Haaland', position: 'ATA', age: 25, overall: 91 },
      { name: 'Sorloth', position: 'ATA', age: 30, overall: 83 },
      { name: 'Nusa', position: 'ATA', age: 21, overall: 78 },
      { name: 'Bobb', position: 'MEI', age: 22, overall: 79 },
      { name: 'Thorstvedt', position: 'VOL', age: 27, overall: 77 },
    ]
  },
  {
    id: 'wc_algeria', name: 'Argélia', shortName: 'ALG', confederation: 'CAF',
    logoUrl: '/world_cup_shields/png/argelia.png',
    logoColor1: '#006233', logoColor2: '#FFFFFF', attack: 81, defense: 79,
    players: [
      { name: 'Mandrea', position: 'GOL', age: 29, overall: 78 },
      { name: 'Ait-Nouri', position: 'LAT', age: 25, overall: 81 },
      { name: 'Bensebaini', position: 'ZAG', age: 31, overall: 80 },
      { name: 'Mandi', position: 'ZAG', age: 34, overall: 78 },
      { name: 'Bennacer', position: 'VOL', age: 28, overall: 83 },
      { name: 'Aouar', position: 'MEI', age: 28, overall: 80 },
      { name: 'Mahrez', position: 'MEI', age: 35, overall: 84 },
      { name: 'Gouiri', position: 'ATA', age: 26, overall: 82 },
      { name: 'Bounedjah', position: 'ATA', age: 34, overall: 79 },
      { name: 'Benrahma', position: 'ATA', age: 30, overall: 80 },
      { name: 'Amoura', position: 'ATA', age: 26, overall: 79 },
    ]
  },
  {
    id: 'wc_jordan', name: 'Jordânia', shortName: 'JOR', confederation: 'AFC',
    logoUrl: '/world_cup_shields/png/jordania.png',
    logoColor1: '#CE1126', logoColor2: '#FFFFFF', attack: 72, defense: 70,
    players: [
      { name: 'Abulaila', position: 'GOL', age: 32, overall: 74 },
      { name: 'Arab', position: 'ZAG', age: 28, overall: 72 },
      { name: 'Nasib', position: 'ZAG', age: 31, overall: 71 },
      { name: 'Haddad', position: 'LAT', age: 34, overall: 73 },
      { name: 'Al-Rashdan', position: 'VOL', age: 26, overall: 72 },
      { name: 'Al-Tamari', position: 'MEI', age: 29, overall: 78 },
      { name: 'Al-Naimat', position: 'ATA', age: 27, overall: 76 },
      { name: 'Olwan', position: 'ATA', age: 24, overall: 73 },
      { name: 'Al-Rawabdeh', position: 'VOL', age: 29, overall: 72 },
      { name: 'Mardi', position: 'MEI', age: 32, overall: 71 },
      { name: 'Al-Fakhouri', position: 'GOL', age: 25, overall: 68 },
    ]
  },
  {
    id: 'wc_ghana', name: 'Gana', shortName: 'GHA', confederation: 'CAF',
    logoUrl: '/world_cup_shields/png/gana.png',
    logoColor1: '#EF2B2D', logoColor2: '#FCD116', attack: 80, defense: 78,
    players: [
      { name: 'Ati-Zigi', position: 'GOL', age: 29, overall: 77 },
      { name: 'Salisu', position: 'ZAG', age: 27, overall: 80 },
      { name: 'Djiku', position: 'ZAG', age: 31, overall: 79 },
      { name: 'Mensah', position: 'LAT', age: 27, overall: 78 },
      { name: 'Partey', position: 'VOL', age: 33, overall: 84 },
      { name: 'Kudus', position: 'MEI', age: 25, overall: 85 },
      { name: 'Nuamah', position: 'MEI', age: 22, overall: 79 },
      { name: 'Jordan Ayew', position: 'ATA', age: 34, overall: 79 },
      { name: 'Inaki Williams', position: 'ATA', age: 32, overall: 82 },
      { name: 'Semenyo', position: 'ATA', age: 26, overall: 79 },
      { name: 'Abdul Samed', position: 'VOL', age: 26, overall: 78 },
    ]
  },
  {
    id: 'wc_panama', name: 'Panamá', shortName: 'PAN', confederation: 'CONCACAF',
    logoUrl: '/world_cup_shields/png/panama.png',
    logoColor1: '#DA121A', logoColor2: '#00205B', attack: 73, defense: 72,
    players: [
      { name: 'Mosquera', position: 'GOL', age: 31, overall: 76 },
      { name: 'Cordoba', position: 'ZAG', age: 25, overall: 77 },
      { name: 'Miller', position: 'ZAG', age: 34, overall: 73 },
      { name: 'Murillo', position: 'LAT', age: 30, overall: 78 },
      { name: 'Carrasquilla', position: 'VOL', age: 27, overall: 78 },
      { name: 'Godoy', position: 'VOL', age: 36, overall: 74 },
      { name: 'Barcenas', position: 'MEI', age: 32, overall: 75 },
      { name: 'Fajardo', position: 'ATA', age: 32, overall: 75 },
      { name: 'Rodriguez', position: 'MEI', age: 27, overall: 74 },
      { name: 'Guerrero', position: 'ATA', age: 26, overall: 72 },
      { name: 'Mejia', position: 'GOL', age: 34, overall: 72 },
    ]
  },
];

// ========== GRUPOS JÁ ESTABELECIDOS (SORTEIO FIXO) ==========

export const ESTABLISHED_GROUPS: { name: string; teamIds: string[] }[] = [
  { name: 'A', teamIds: ['wc_mexico', 'wc_southafrica', 'wc_southkorea', 'wc_czech'] },
  { name: 'B', teamIds: ['wc_canada', 'wc_bosnia', 'wc_qatar', 'wc_switzerland'] },
  { name: 'C', teamIds: ['wc_brazil', 'wc_morocco', 'wc_haiti', 'wc_scotland'] },
  { name: 'D', teamIds: ['wc_usa', 'wc_paraguay', 'wc_australia', 'wc_turkey'] },
  { name: 'E', teamIds: ['wc_germany', 'wc_curacao', 'wc_ivorycoast', 'wc_ecuador'] },
  { name: 'F', teamIds: ['wc_netherlands', 'wc_japan', 'wc_sweden', 'wc_tunisia'] },
  { name: 'G', teamIds: ['wc_belgium', 'wc_egypt', 'wc_iran', 'wc_newzealand'] },
  { name: 'H', teamIds: ['wc_spain', 'wc_capeverde', 'wc_saudiarabia', 'wc_uruguay'] },
  { name: 'I', teamIds: ['wc_france', 'wc_senegal', 'wc_iraq', 'wc_norway'] },
  { name: 'J', teamIds: ['wc_argentina', 'wc_algeria', 'wc_austria', 'wc_jordan'] },
  { name: 'K', teamIds: ['wc_portugal', 'wc_drcongo', 'wc_uzbekistan', 'wc_colombia'] },
  { name: 'L', teamIds: ['wc_england', 'wc_croatia', 'wc_ghana', 'wc_panama'] },
];

// Exportar times construídos
export const getWorldCupTeams = (): Team[] => WC_TEAMS_DATA.map(buildWCTeam);

// Mapa de confederação por ID de time
export const getTeamConfederation = (teamId: string): WCConfederation => {
  const data = WC_TEAMS_DATA.find(t => t.id === teamId);
  return data?.confederation ?? 'UEFA';
};
